cd ab_3w &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,force_z,alpha,beta,distance_ceiling --target normalized_moment --backend gpytorch --alpha 0.001 --save-model ../gpr_moment_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_moment_ab_3w.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,force_z,alpha,beta,distance_ceiling --target force_y --backend gpytorch --alpha 0.001 --save-model ../gpr_force_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_force_ab_3w.png &&

cd .. &&

cd plot_3w &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s-15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s-15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s-15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s0_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s0_fz12.5.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s0_fz12.5.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=12.5 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&

cd .. &&

cd effect/ab_3w &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix distance_ceiling=1.0 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_3w_dc1.0_norm.png --output-csv gpr_effects_combined_3w_dc1.0_norm.csv --verbose --transparent t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix distance_ceiling=1.5 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_3w_dc1.5_norm.png --output-csv gpr_effects_combined_3w_dc1.5_norm.csv --verbose --transparent t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix distance_ceiling=2.0 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_3w_dc2.0_norm.png --output-csv gpr_effects_combined_3w_dc2.0_norm.csv --verbose --transparent t && 

cd ../.. &&

ls