# prop coef finder
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.000 -p max_thrust:=0.400 -p step_duration:=1.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=5 -p filename_prefix:=thrust -p enable_breakpoint:=False -p coef_name:=linear -p sensor_reversed:=false -p skip_sensor_calibration:=false


# gpr
## alpha-beta 2w
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target normalized_moment --backend gpytorch --save-model ../gpr_moment_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_moment_ab.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target force_y --backend gpytorch --save-model ../gpr_force_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_force_ab.png

## alpha-beta 3w
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,wall_spacing,force_z,alpha,beta,distance_ceiling --target normalized_moment --backend gpytorch --save-model ../gpr_moment_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_moment_ab_3w.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,wall_spacing,force_z,alpha,beta,distance_ceiling --target force_y --backend gpytorch --save-model ../gpr_force_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_force_ab_3w.png

# moment vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&


# moment vs distance (hue wall spacing)
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=25 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s0_fz25.png --fix tilt_angle=0 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t

# moment vs distance (3 walls)
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s-15_fz20.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s-15_fz20.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s-15_fz20.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s0_fz20.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s0_fz20.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s0_fz20.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s15_fz20.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s15_fz20.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s15_fz20.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&

# force vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&


# postprocess

cd 20251105wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251203wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251212wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251214wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251215wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251216wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251222wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251224wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&

cd 20251105wef/meas && mv concat_merged.csv ../../concat_merged_20251105wef.csv && cd ../.. &&
cd 20251203wef/meas && mv concat_merged.csv ../../concat_merged_20251203wef.csv && cd ../.. &&
cd 20251212wef/meas && mv concat_merged.csv ../../concat_merged_20251212wef.csv && cd ../.. &&
cd 20251214wef/meas && mv concat_merged.csv ../../concat_merged_20251214wef.csv && cd ../.. &&
cd 20251215wef/meas && mv concat_merged.csv ../../concat_merged_20251215wef.csv && cd ../.. &&
cd 20251216wef/meas && mv concat_merged.csv ../../concat_merged_20251216wef.csv && cd ../.. &&
cd 20251222wef/meas && mv concat_merged.csv ../../concat_merged_20251222wef.csv && cd ../.. &&
cd 20251224wef/meas && mv concat_merged.csv ../../concat_merged_20251224wef.csv && cd ../.. &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&



# combined alpha beta

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima-plot --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.60_norm.png --output-csv gpr_effects_combined_2w1.60_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima-plot --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.20_norm.png --output-csv gpr_effects_combined_2w1.20_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima-plot --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.05_norm.png --output-csv gpr_effects_combined_2w1.05_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima-plot --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w0.90_norm.png --output-csv gpr_effects_combined_2w0.90_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima-plot --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w0.75_norm.png --output-csv gpr_effects_combined_2w0.75_norm.csv &&



# combined

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w0.75_norm.png &&



# combined prop_spacing_x and prop_spacing_y

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref prop_spacing_x=0.25,prop_spacing_y=0.25 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Prop Spacing X [m]" --ylabel "Prop Spacing Y [m]" --output-eval gpr_effects_combined_2w1.60_norm.png



# combined alpha beta 3 walls

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix distance_ceiling=1.0 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_3w_dc1.0_norm.png --output-csv gpr_effects_combined_3w_dc1.0_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix distance_ceiling=1.5 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_3w_dc1.5_norm.png --output-csv gpr_effects_combined_3w_dc1.5_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix distance_ceiling=2.0 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_3w_dc2.0_norm.png --output-csv gpr_effects_combined_3w_dc2.0_norm.csv &&



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.75.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.75.png &&


# visualize 3d morph
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-15" --save "t-15_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-15" --save "t0_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-15" --save "t15_f0_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-0" --save "t-15_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-0" --save "t15_f0_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="15" --save "t-15_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="15" --save "t0_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="15" --save "t15_f0_s15.png" &&  

# visualize 3d morph, with title
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-15" --save "t-15_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-15" --save "t0_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-15" --save "t15_f0_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-0" --save "t-15_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-0" --save "t15_f0_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="15" --save "t-15_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="15" --save "t0_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="15" --save "t15_f0_s15.png" &&  

# visualize 3d morph, alpha - beta
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha "-30" --beta="-30" --save "alpha-30_beta-30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="-30" --save "alpha0_beta-30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="-30" --save "alpha30_beta-30.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-30" --beta="0" --save "alpha-30_beta0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="0" --save "alpha0_beta0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="0" --save "alpha30_beta0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-30" --beta="30" --save "alpha-30_beta30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="30" --save "alpha0_beta30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="30" --save "alpha30_beta30.png" &&  

# --- GAM (解釈目的) ---
# 目的変数を切り替え可能（例: torque_x / force_y）で、
# 平均モデル + 分散モデル(log(variance_*)) を同時に当てて、重要度と部分効果プロットを出力します。
source ~/colcon_ws/src/drone_thrust_analyzer/.venv-mpl/bin/activate

# torque_x（対応する分散: variance_torque_x を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged.csv \
  --target torque_x \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_torque_x

# force_y（対応する分散: variance_force_y を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged.csv \
  --target force_y \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_force_y