# moment vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&

# force vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_20251221.csv --load-model ../gpr_force.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&


cd 20251105wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&
cd 20251203wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&
cd 20251212wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&
cd 20251214wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&
cd 20251215wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&
cd 20251216wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 && cd ../.. &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&


# combined alpha beta

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0 --fix prop_spacing_y=0 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0 --fix prop_spacing_y=0 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0 --fix prop_spacing_y=0 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0 --fix prop_spacing_y=0 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0 --fix prop_spacing_y=0 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --output-eval gpr_effects_combined_2w0.75_norm.png &&

# combined

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --output-eval gpr_effects_combined_2w0.75_norm.png &&

# combined prop_spacing_x and prop_spacing_y

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_20251221.csv --load-model ../../gpr_moment.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref prop_spacing_x=0.25,prop_spacing_y=0.25 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Prop Spacing X [m]" --ylabel "Prop Spacing Y [m]" --output-eval gpr_effects_combined_2w1.60_norm.png



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.75.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged_20251221.csv --load-model ../gpr_moment.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.75.png &&


# --- GAM (解釈目的) ---
# 目的変数を切り替え可能（例: torque_x / force_y）で、
# 平均モデル + 分散モデル(log(variance_*)) を同時に当てて、重要度と部分効果プロットを出力します。
source ~/colcon_ws/src/drone_thrust_analyzer/.venv-mpl/bin/activate

# torque_x（対応する分散: variance_torque_x を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged_20251221.csv \
  --target torque_x \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_torque_x

# force_y（対応する分散: variance_force_y を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged_20251221.csv \
  --target force_y \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_force_y