cd ab &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target normalized_moment --backend gpytorch --alpha 0.001 --save-model ../gpr_moment_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_moment_ab.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target force_y --backend gpytorch --alpha 0.001 --save-model ../gpr_force_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_force_ab.png && 

cd .. &&
cd plot_1w &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --figsize 10,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&

cd .. &&
cd plot_2w &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s-15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s-15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s-15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s0_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s0_fz12.5.png --fix tilt_angle=0 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s0_fz12.5.png --fix tilt_angle=15 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --figsize 10,4 --no-uncertainty --x-domain-per-hue-raw t &&

cd .. &&
cd effect/ab &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine fscore --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_2w1.60_norm.png --output-csv gpr_effects_combined_2w1.60_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine fscore --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_2w1.20_norm.png --output-csv gpr_effects_combined_2w1.20_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine fscore --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_2w1.05_norm.png --output-csv gpr_effects_combined_2w1.05_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine fscore --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_2w0.90_norm.png --output-csv gpr_effects_combined_2w0.90_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine fscore --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --output-eval gpr_effects_combined_2w0.75_norm.png --output-csv gpr_effects_combined_2w0.75_norm.csv &&

cd ../.. &&
ls