# prop coef finder
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.000 -p max_thrust:=0.400 -p step_duration:=1.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=5 -p filename_prefix:=thrust -p enable_breakpoint:=False -p coef_name:=linear -p sensor_reversed:=false -p skip_sensor_calibration:=false

# fix scaling
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/scale_csv_columns.py \
  -i concat_* \
  --output-dir . \
  --scale "force_x,force_x_bias_corrected,bias_force_x:0.505" \
  --scale "force_y,force_y_bias_corrected,bias_force_y:0.498" \
  --scale "force_z,force_z_bias_corrected,bias_force_z:0.493" \
  --scale "torque_x,torque_x_bias_corrected,bias_torque_x:0.200" \
  --scale "torque_y,torque_y_bias_corrected,bias_torque_y:0.199" \
  --scale "torque_z,torque_z_bias_corrected,bias_torque_z:0.197" \
  --scale "variance_force_x,variance_force_x_bias_corrected,variance_bias_force_x:0.255" \
  --scale "variance_force_y,variance_force_y_bias_corrected,variance_bias_force_y:0.248" \
  --scale "variance_force_z,variance_force_z_bias_corrected,variance_bias_force_z:0.243" \
  --scale "variance_torque_x,variance_torque_x_bias_corrected,variance_bias_torque_x:0.0402" \
  --scale "variance_torque_y,variance_torque_y_bias_corrected,variance_bias_torque_y:0.0397" \
  --scale "variance_torque_z,variance_torque_z_bias_corrected,variance_bias_torque_z:0.0388" \
  --scale "target_thrust,base_thrust,base_thrust_z,normalized_thrust,thrust_coefficient:0.5" \
  --scale "normalized_moment:0.406"

# condition counter (count unique experimental conditions)
# wall_spacing fixed (1.6)
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/condition_counter.py \
  --input merged.csv \
  --condition-cols distance target_thrust tilt_angle fold_angle slant_angle wall_spacing \
  --fix wall_spacing=1.6

# wall_spacing not fixed
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/condition_counter.py \
  --input merged.csv \
  --condition-cols distance target_thrust tilt_angle fold_angle slant_angle wall_spacing

# gpr
## alpha-beta 2w
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target normalized_moment --backend gpytorch --alpha 0.001 --save-model ../gpr_moment_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_moment_ab.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged.csv --features distance,wall_spacing,force_z,alpha,beta,prop_spacing_x,prop_spacing_y --target force_y --backend gpytorch --alpha 0.001 --save-model ../gpr_force_ab.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue fold_angle --output gpr_force_ab.png

## alpha-beta 3w
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,force_z,alpha,beta,distance_ceiling --target normalized_moment --backend gpytorch --alpha 0.001 --save-model ../gpr_moment_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_moment_ab_3w.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gaussian_process_regression.py ../merged_3w.csv --features distance,force_z,alpha,beta,distance_ceiling --target force_y --backend gpytorch --alpha 0.001 --save-model ../gpr_force_ab_3w.pkl --trust-model t --plot-raw-fit t --row-group-by slant_angle --col-group-by tilt_angle --curve-x distance --raw-alpha 0.05 --hue distance_ceiling --output gpr_force_ab_3w.png

# moment vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 5.0,12.5 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 5.0,12.5 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_m_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-7,7" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Vertical Thrust [N]" --transparent t --figsize 14,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t --fit-extrema-reverse-colors t  &&

# --- Slide overlay: 1-wall vs 2-wall vs 3-wall (transparent, fixed axes, no hue) ---
# 目的: PowerPoint 上で重ねられるように、各環境を個別PNG(透過)で出力する。
# 固定軸: x=[0.4,1.8], y=[-12,7]
# 線色: 1-wall=#0070C0, 2-wall=#00B050, 3-wall=#D63225
# 姿勢: (tilt, fold, slant) = (0,0,0) と (15,0,-15)

## pose (0,0,0), (15, 0, -15)
# --- base (axes only; no plot) ---
# PowerPoint の下敷き（軸・ラベル・グリッドのみ）として使う。
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=1.6 --fix tilt_angle=0 --fix fold_angle=0 --fix slant_angle=0 --trust-model t --output slide_overlay_base_axes_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid t --drone f --raw-alpha 0.0 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --no-plot t --bbox-tight f --save-dpi 300 &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=1.6 --fix tilt_angle=15 --fix fold_angle=0 --fix slant_angle=-15 --trust-model t --output slide_overlay_base_axes_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid t --drone f --raw-alpha 0.0 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --no-plot t --bbox-tight f --save-dpi 300 &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=1.6 --fix tilt_angle=0 --fix fold_angle=0 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_wide_1w_ws1.60_t0_f0_s0.png --xlim="0.5,6.5" --ylim="-17,7" --no-title --legend f --grid t --drone f --raw-alpha 0.1 --raw-color "#0070C0" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 14,4 --no-uncertainty --fit-color "#0070C0" --bbox-tight f --save-dpi 300

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=1.6 --fix tilt_angle=0 --fix fold_angle=0 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_1w_ws1.60_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#0070C0" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#0070C0" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=0.75 --fix tilt_angle=0 --fix fold_angle=0 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_2w_ws0.75_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#00B050" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#00B050" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=1.6 --fix tilt_angle=15 --fix fold_angle=0 --fix slant_angle=-15 --trust-model t --output slide_overlay_moment_1w_ws1.60_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#0070C0" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#0070C0" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --fix wall_spacing=0.75 --fix tilt_angle=15 --fix fold_angle=0 --fix slant_angle=-15 --trust-model t --output slide_overlay_moment_2w_ws0.75_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#00B050" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#00B050" --bbox-tight f --save-dpi 300 --mask-outside-plot t

## 3-wall
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=2 --fix tilt_angle=0 --fix fold_angle=15 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_3w_dc2.0_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#F79222" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#F79222" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=2 --fix tilt_angle=15 --fix fold_angle=15 --fix slant_angle=-15 --trust-model t --output slide_overlay_moment_3w_dc2.0_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#F79222" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#F79222" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=1.5 --fix tilt_angle=0 --fix fold_angle=15 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_3w_dc1.5_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#D63225" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#D63225" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=1.5 --fix tilt_angle=15 --fix fold_angle=15 --fix slant_angle=-15 --trust-model t --output slide_overlay_moment_3w_dc1.5_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#D63225" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#D63225" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=1 --fix tilt_angle=0 --fix fold_angle=15 --fix slant_angle=0 --trust-model t --output slide_overlay_moment_3w_dc1.0_t0_f0_s0.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#D63225" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#D63225" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --fix distance_ceiling=1 --fix tilt_angle=15 --fix fold_angle=15 --fix slant_angle=-15 --trust-model t --output slide_overlay_moment_3w_dc1.0_t15_f0_s-15.png --xlim="0.4,1.8" --ylim="-17,7" --no-title --legend f --grid f --drone f --raw-alpha 0.1 --raw-color "#D63225" --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --transparent t --figsize 8,4 --no-uncertainty --fit-color "#D63225" --bbox-tight f --save-dpi 300 --mask-outside-plot t &&


# moment vs distance (hue wall spacing)
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s-15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s-15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s-15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=-15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s0_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s0_fz12.5.png --fix tilt_angle=0 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s0_fz12.5.png --fix tilt_angle=15 --fix slant_angle=0 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t-15_f0_s15_fz12.5.png --fix tilt_angle=-15 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t0_f0_s15_fz12.5.png --fix tilt_angle=0 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_moment_ab.pkl --curve-x distance --hue-raw wall_spacing --hue-raw-cmap viridis --hue-raw-range 0.75,1.6 --hue-fit wall_spacing --hue-fit-cmap viridis --hue-fit-range 0.75,1.6 --fix target_thrust=12.5 --fix fold_angle=0 --trust-model t --output plot_hue_ws_m_t15_f0_s15_fz12.5.png --fix tilt_angle=15 --fix slant_angle=15 --fix fold_angle=0 --ylim="-12,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Wall Spacing [m]" --transparent t --figsize 14,4 --no-uncertainty --x-domain-per-hue-raw t &&

# moment vs distance (3 walls)
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s-15_fz20.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s-15_fz20.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s-15_fz20.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s0_fz20.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s0_fz20.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s0_fz20.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t-15_f0_s15_fz20.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t0_f0_s15_fz20.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged_3w.csv --load-model ../gpr_moment_ab_3w.pkl --curve-x distance --hue-raw distance_ceiling --hue-raw-cmap viridis --hue-raw-range 1.0,2.0 --hue-fit distance_ceiling --hue-fit-cmap viridis --hue-fit-range 1.0,2.0 --fix target_thrust=20 --fix wall_spacing=0.75 --fix fold_angle=15 --trust-model t --output plot_m_t15_f0_s15_fz20.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-24,12" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Normalized Moment [%]" --colorbar-label "Ceiling Distance [R]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t  &&

# force vs distance plot

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s-15.png --fix tilt_angle=-15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s-15.png --fix tilt_angle=0 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s-15.png --fix tilt_angle=15 --fix slant_angle=-15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s0.png --fix tilt_angle=-15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s0.png --fix tilt_angle=0 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s0.png --fix tilt_angle=15 --fix slant_angle=0 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t-15_f0_s15.png --fix tilt_angle=-15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t0_f0_s15.png --fix tilt_angle=0 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_gpytorch_fit_curve_with_raw.py ../merged.csv --load-model ../gpr_force_ab.pkl --curve-x distance --hue-raw target_thrust --hue-raw-cmap viridis --hue-raw-range 10.0,25.0 --hue-fit force_z --hue-fit-cmap viridis --hue-fit-range 10.0,25.0 --fix wall_spacing=1.6 --fix fold_angle=0 --trust-model t --output plot_f_t15_f0_s15.png --fix tilt_angle=15 --fix slant_angle=15 --ylim="-0.05,0.3" --no-title --drone f --raw-alpha 0.1 --xlabel "Distance [R]" --ylabel "Force [N]" --colorbar-label "Vertical Thrust [N]" --figsize 6,4 --no-uncertainty --fit-extrema t --fit-extrema-marker t --fit-extrema-vline t &&


# postprocess

cd 20251105wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251203wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251212wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251214wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251215wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251216wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251222wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&
cd 20251224wef/meas && python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/postprocess_all.py -j 8 --recreate-corrected && cd ../.. &&

cd 20251105wef/meas && mv concat_merged.csv ../../concat_merged_20251105wef.csv && cd ../.. &&
cd 20251203wef/meas && mv concat_merged.csv ../../concat_merged_20251203wef.csv && cd ../.. &&
cd 20251212wef/meas && mv concat_merged.csv ../../concat_merged_20251212wef.csv && cd ../.. &&
cd 20251214wef/meas && mv concat_merged.csv ../../concat_merged_20251214wef.csv && cd ../.. &&
cd 20251215wef/meas && mv concat_merged.csv ../../concat_merged_20251215wef.csv && cd ../.. &&
cd 20251216wef/meas && mv concat_merged.csv ../../concat_merged_20251216wef.csv && cd ../.. &&
cd 20251222wef/meas && mv concat_merged.csv ../../concat_merged_20251222wef.csv && cd ../.. &&
cd 20251224wef/meas && mv concat_merged.csv ../../concat_merged_20251224wef.csv && cd ../.. &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.60_norm.png  &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_abs_2w0.75_norm.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --colormap custom_rdbu --heatmap-range="-100,300" --transparent t --output-eval gpr_effects_moment_grad_abs_2w0.75_norm.png &&



# combined alpha beta

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.60 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,6.20 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_2w1.60_norm.png --output-csv gpr_effects_combined_2w1.60_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.20 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,4.25 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_2w1.20_norm.png --output-csv gpr_effects_combined_2w1.20_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=1.05 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,3.35 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_2w1.05_norm.png --output-csv gpr_effects_combined_2w1.05_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=0.90 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,2.60 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_2w0.90_norm.png --output-csv gpr_effects_combined_2w0.90_norm.csv &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:5.0,12.5:5 --fix wall_spacing=0.75 --fix prop_spacing_x=0.25 --fix prop_spacing_y=0.25 --integrate-over distance:0.0,1.70 --viz-range alpha:-40.0,40.0:30 --viz-range beta:-40.0,40.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_rwg --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_2w0.75_norm.png --output-csv gpr_effects_combined_2w0.75_norm.csv &&



# combined

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --fix fold_angle=0 --integrate-over distance:0.0,6.20 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --transparent t --output-eval gpr_effects_combined_2w1.60_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --fix fold_angle=0 --integrate-over distance:0.0,4.25 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --transparent t --output-eval gpr_effects_combined_2w1.20_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --fix fold_angle=0 --integrate-over distance:0.0,3.35 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --transparent t --output-eval gpr_effects_combined_2w1.05_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --fix fold_angle=0 --integrate-over distance:0.0,2.60 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --transparent t --output-eval gpr_effects_combined_2w0.90_norm.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_tfs.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --fix fold_angle=0 --integrate-over distance:0.0,1.70 --viz-range tilt_angle:-30.0,30.0:30 --viz-range slant_angle:-15.0,15.0:30 --overlay-raw --cumulative-over force_z:3 --normalize-ref tilt_angle=0.0,slant_angle=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --mask-by-convex-hull fix --find-optima --optima-objective max --optima-window --optima-window-shape circle --optima-window-size 5 --optima-window-stride "2,2" --optima-plot-label rank_value --xlabel "Tilt Angle [deg]" --ylabel "Slant Angle [deg]" --transparent t --output-eval gpr_effects_combined_2w0.75_norm.png &&



# combined prop_spacing_x and prop_spacing_y

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged.csv --load-model ../../gpr_moment_ab.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref prop_spacing_x=0.25,prop_spacing_y=0.25 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --no-colorbar --xlabel "Prop Spacing X [m]" --ylabel "Prop Spacing Y [m]" --transparent t --output-eval gpr_effects_combined_2w1.60_norm.png



# combined alpha beta 3 walls

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix distance_ceiling=1.0 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_3w_dc1.0_norm.png --output-csv gpr_effects_combined_3w_dc1.0_norm.csv --verbose &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix distance_ceiling=1.5 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_3w_dc1.5_norm.png --output-csv gpr_effects_combined_3w_dc1.5_norm.csv --verbose &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../../merged_3w.csv --load-model ../../gpr_moment_ab_3w.pkl --device cpu --trust-model t --metrics moment_abs,grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix distance_ceiling=2.0 --integrate-over distance:0.0,2.10 --viz-range alpha:-30.0,30.0:30 --viz-range beta:-30.0,30.0:30 --overlay-raw-all --cumulative-over force_z:3 --normalize-ref alpha=0.0,beta=0.0 --normalize-ref-per-step --normalize-as-change-rate --combine logsum --colormap custom_improve --heatmap-range="-100,100" --no-title --mask-by-convex-hull all --optima --xlabel "Alpha [deg]" --ylabel "Beta [deg]" --colorbar-label "Improvement [%]" --transparent t --output-eval gpr_effects_combined_3w_dc2.0_norm.png --output-csv gpr_effects_combined_3w_dc2.0_norm.csv --verbose &&



python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric moment_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_abs_2w0.75.png &&

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.60 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,6.20 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.60.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.20 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,4.25 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.20.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=1.05 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,3.35 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w1.05.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.90 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,2.60 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.90.png &&
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gpr_effects_analysis.py ../merged.csv --load-model ../gpr_moment_ab.pkl --device cpu --trust-model t --metric grad_abs --grad-dims distance --integrate-over force_z:10.0,25.0:5 --fix wall_spacing=0.75 --integrate-over alpha:auto,auto:5 --integrate-over beta:auto,auto:5 --integrate-over distance:0.0,1.70 --viz-range prop_spacing_x:auto,auto:10 --viz-range prop_spacing_y:auto,auto:10 --overlay-raw-all --cumulative-over force_z:3 --transparent t --output-eval gpr_effects_vs_prop_spacing_xy_moment_grad_abs_2w0.75.png &&


# visualize 3d morph
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="-15" --psi="-15" --save "t-15_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="0" --psi="-15" --save "t0_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="15" --psi="-15" --save "t15_f0_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="-15" --psi="-0" --save "t-15_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="0" --psi="-0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="15" --psi="-0" --save "t15_f0_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="-15" --psi="15" --save "t-15_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="0" --psi="15" --save "t0_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-show --save-split \
  --theta="15" --psi="15" --save "t15_f0_s15.png" &&  


# visualize 3d morph (w/o y0 wall)
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="-15" --psi="-15" --save "t-15_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="0" --psi="-15" --save "t0_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="15" --psi="-15" --save "t15_f0_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="-15" --psi="-0" --save "t-15_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="0" --psi="-0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="15" --psi="-0" --save "t15_f0_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="-15" --psi="15" --save "t-15_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="0" --psi="15" --save "t0_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --drone-lw 2.5 --no-y0-plane --no-show --save-split \
  --theta="15" --psi="15" --save "t15_f0_s15.png" &&  


# visualize 3d morph (fold 15deg)
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-15" --phi="15" --save "t-15_f15_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-15" --phi="15" --save "t0_f15_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-15" --phi="15" --save "t15_f15_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-0" --phi="15" --save "t-15_f15_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-0" --phi="15" --save "t0_f15_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-0" --phi="15" --save "t15_f15_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="15" --phi="15" --save "t-15_f15_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="15" --phi="15" --save "t0_f15_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="15" --phi="15" --save "t15_f15_s15.png" &&  


# visualize 3d morph, black, bold
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --drone-lw 3 --drone-color black --view-azim 20 --view-elev 12 --no-y0-plane --no-show --save-split \
  --theta="0" --psi="0" --phi="0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --drone-lw 3 --drone-color "#0070C0" --view-azim 20 --view-elev 12 --no-y0-plane --no-show --save-split \
  --theta="15" --psi="-15" --phi="15" --save "t15_f15_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --drone-lw 3 --drone-color black --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="0" --phi="0" --save "t0_f0_s0_1w.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --drone-lw 3 --drone-color "#0070C0" --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-15" --phi="15" --save "t15_f15_s-15_1w.png" &&
  

# visualize 3d morph, with title
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-15" --save "t-15_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-15" --save "t0_f0_s-15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-15" --save "t15_f0_s-15.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="-0" --save "t-15_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="-0" --save "t0_f0_s0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="-0" --save "t15_f0_s0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-15" --psi="15" --save "t-15_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="0" --psi="15" --save "t0_f0_s15.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="15" --psi="15" --save "t15_f0_s15.png" &&  

# visualize 3d morph, alpha - beta
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha "-30" --beta="-30" --save "alpha-30_beta-30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="-30" --save "alpha0_beta-30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="-30" --save "alpha30_beta-30.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-30" --beta="0" --save "alpha-30_beta0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="0" --save "alpha0_beta0.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="0" --save "alpha30_beta0.png" &&  
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-30" --beta="30" --save "alpha-30_beta30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="0" --beta="30" --save "alpha0_beta30.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="30" --beta="30" --save "alpha30_beta30.png" &&  


# visualize 3d morph, alpha - beta (optima)

# 2w1.60
# #1 73% at (1.38, -15.2)
# #2 68% at (-9.66, -23.4)

# 2w1.05
# #1 71% at (-6.9, -23.4)
# #2 60% at (23.4, -20.7)

# 2w0.75
# #1 90% at (4.14, -29.0)

# 3w0.75_dc2.0
# #1 5% at (11.4, 9.31)
# #2 5% at (5.17, -19.7)
# #3 5% at (-19.7, -5.17)

# 3w0.75_dc1.0
# #1 22% at (-3.1, 13.4)
# #2 19% at (3.1, 5.17)

# visualize 3d morph, alpha - beta (optima; per env)


python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="1.38" --beta="-15.20" --save "optima_2w1.60_rank1_73pct_a1.38_b-15.20.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-9.66" --beta="-23.40" --save "optima_2w1.60_rank2_68pct_a-9.66_b-23.40.png" &&

python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-6.90" --beta="-23.40" --save "optima_2w1.05_rank1_71pct_a-6.90_b-23.40.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="23.40" --beta="-20.70" --save "optima_2w1.05_rank2_60pct_a23.40_b-20.70.png" &&

python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="4.14" --beta="-29.00" --save "optima_2w0.75_rank1_90pct_a4.14_b-29.00.png" &&

python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="11.40" --beta="9.31" --save "optima_3w0.75_dc2.0_rank1_5pct_a11.40_b9.31.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="5.17" --beta="-19.70" --save "optima_3w0.75_dc2.0_rank2_5pct_a5.17_b-19.70.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-19.70" --beta="-5.17" --save "optima_3w0.75_dc2.0_rank3_5pct_a-19.70_b-5.17.png" &&

python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="-3.10" --beta="13.40" --save "optima_3w0.75_dc1.0_rank1_22pct_a-3.10_b13.40.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split --solve-psi-theta --drone-lw 2.5 \
  --alpha="3.10" --beta="5.17" --save "optima_3w0.75_dc1.0_rank2_19pct_a3.10_b5.17.png"

# visualize 3d morph, with grid

python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --save-split --dot-grid "frame=rotor_between;rotors=3,0;origin=0,0.03,0.08889;u=0,0.015,0;v=0,0,0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,0.03,-0.08889;u=0,0.015,0;v=0,0,-0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,-0.03,0.08889;u=0,-0.015,0;v=0,0,0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,-0.03,-0.08889;u=0,-0.015,0;v=0,0,-0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --theta="0" --psi="-0" --save "t0_f0_s0_w_grid.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --save-split --dot-grid "frame=rotor_between;rotors=3,0;origin=0,0.03,0.08889;u=0,0.015,0;v=0,0,0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,0.03,-0.08889;u=0,0.015,0;v=0,0,-0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,-0.03,0.08889;u=0,-0.015,0;v=0,0,0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --dot-grid "frame=rotor_between;rotors=3,0;origin=0,-0.03,-0.08889;u=0,-0.015,0;v=0,0,-0.04445;nu=14;nv=3;color=black;alpha=0.8;size=10;marker=." --theta="15" --psi="-15" --save "t15_f0_s-15_w_grid.png" &&

# flow

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/plot_flow_line_facet.py --input concat_merged.csv --col-keys tilt_angle slant_angle --y-in-origin 266.7 --x-offset-max-mm 20 --single-angle-mode use --plot-kind mean_fold_with_map --feature u_norm_o --x-offset-scope io_y_facet --fit-sensor-k --export-k flow_k_fit.csv --k-scope io_y_facet --overlay-drone --drone-prop-center-y-mm 88.9 --drone-arm-length 0.128 --drone-rotor-inflow-offset-mm 14 --hide-in-line --hide-xc --plot-xc-on-map --xlabel "y [mm]" --ylabel "|U| [%]" --xlabel-map "y [mm]" --ylabel-map "|U| [%]" --cmap-in viridis --cmap-out magma --cbar-label-in "in: |U| [%]" --cbar-label-out "out: |U| [%]" --output flow_facet.png --figsize 12 12


# optimize morph

python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/search_morph_by_ab_map.py --value-col value --tilt="-30,30:60" --fold="0,15:15" --slant="-15,15:60" --hierarchy slant:tilt,fold --map-csv maps/2w1.60.csv --map-csv maps/2w1.05.csv --map-csv maps/2w0.75.csv --map-csv maps/3w0.75_dc1.0.csv --map-csv maps/3w0.75_dc2.0.csv
 
# visualize 3d morph (hierarchy best env0~4; slant fixed)
# slant=7.00
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="30.00" --psi="7.00" --phi="5.36" --save "hier_best_2w1.60_t30.00_s7.00_f5.36_a27.76_b-15.46.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="25.93" --psi="7.00" --phi="0.00" --save "hier_best_2w1.05_t25.93_s7.00_f0.00_a23.42_b-14.55.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="16.78" --psi="7.00" --phi="0.00" --save "hier_best_2w0.75_t16.78_s7.00_f0.00_a16.79_b-7.29.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="-11.69" --psi="7.00" --phi="0.00" --save "hier_best_3w0.75_dc1.0_t-11.69_s7.00_f0.00_a-3.47_b13.19.png" &&
python ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/visualize_morph_drone.py --arm-length 0.12 --three-view --hide-decorations --drone-center-y 0.3 --rotor-inflow-offset 0.011 --view-azim 20 --view-elev 12 --no-show --save-split \
  --theta="3.56" --psi="7.00" --phi="13.93" --save "hier_best_3w0.75_dc2.0_t3.56_s7.00_f13.93_a6.68_b4.17.png"





# --- GAM (解釈目的) ---
# 目的変数を切り替え可能（例: torque_x / force_y）で、
# 平均モデル + 分散モデル(log(variance_*)) を同時に当てて、重要度と部分効果プロットを出力します。
source ~/colcon_ws/src/drone_thrust_analyzer/.venv-mpl/bin/activate

# torque_x（対応する分散: variance_torque_x を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged.csv \
  --target torque_x \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_torque_x

# force_y（対応する分散: variance_force_y を自動推定）
python3 ~/colcon_ws/src/drone_thrust_analyzer/auto_thrust_recorder/scripts/gam_analysis.py ../../merged.csv \
  --target force_y \
  --features distance,target_thrust,wall_spacing,tilt_angle,fold_angle,slant_angle \
  --outdir gam_out \
  --prefix gam_force_y