ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=0.50[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=0.65[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=0.80[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=1.00[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=1.25[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=1.50[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=2.00[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=2.50[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=3.00[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=4.00[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=2 -p filename_prefix:=distance=5.00[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front -p enable_breakpoint:=False