ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=0.50R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=0.65R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=0.80R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=1.00R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=1.25R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=1.50R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=2.00R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=2.50R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=3.00R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=4.00R_tilt8deg_fold15deg_right -p enable_breakpoint:=False &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.0 -p max_thrust:=21.0 -p step_duration:=5.0 -p step_size:=1.5 -p num_repetitions:=8 -p filename_prefix:=5.00R_tilt8deg_fold15deg_right -p enable_breakpoint:=False