ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.65[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.80[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.25[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=2.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=2.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=5.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=7.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=9.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false

ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.0 -p max_thrust:=0.4 -p step_duration:=1.0 -p step_size:=0.01 -p mode:=linear -p num_repetitions:=4 -p filename_prefix:=distance=9.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false

ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.65[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=0.80[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.25[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=1.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=2.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=2.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.75[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.20[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.35[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false


ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false && 
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.35[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false && 
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.35[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=4.00[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.75[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=10.0 -p max_thrust:=25.0 -p step_duration:=1.5 -p step_size:=1.0 -p mode:=polynomial -p num_repetitions:=4 -p filename_prefix:=distance=3.50[R]_tilt=0[deg]_fold=15[deg]_wheelbase=2.7[R]_direction=front_height=0[mm] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold15deg -p sensor_reversed:=false


# thrust
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.000 -p max_thrust:=0.400 -p step_duration:=1.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=8 -p filename_prefix:=thrust_tilt0deg_fold0deg -p enable_breakpoint:=False -p sensor_reversed:=false && ls


# flow
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.240[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.200[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.160[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.120[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.080[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false &&
ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=15.000 -p max_thrust:=15.000 -p step_duration:=10.000 -p step_size:=1.500 -p mode:=polynomial -p num_repetitions:=1 -p filename_prefix:=distance=1.000[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.040[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false -p autoexit:=false



ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 40.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=0[deg]_fold=0[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.0400[m] -p enable_breakpoint:=False -p coef_name:=tilt0deg_fold0deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 60.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.0600[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 80.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.0800[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 100.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.1000[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 120.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.1200[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 140.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.1400[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 160.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.1600[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 180.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.1800[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
ros2 service call /move_mm   dynamixel_leadscrew_slider_msgs/srv/SetPositionMm   '{target_mm: 200.00}' &&ros2 run dynamixel_linear_slider position_command_and_wait_node --ros-args -p target_position:=-0.258350 && ros2 run auto_thrust_recorder auto_thrust_recorder --ros-args -p min_thrust:=0.300 -p max_thrust:=0.300 -p step_duration:=10.000 -p step_size:=0.010 -p mode:=linear -p num_repetitions:=1 -p filename_prefix:=distance=0.500[R]_tilt=30[deg]_fold=15[deg]_wheelbase=2.700[R]_direction=front_height=0.000[mm]_flowdistance=0.2000[m] -p enable_breakpoint:=False -p coef_name:=tilt30deg_fold15deg -p sensor_reversed:=false &&
