import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from criteria_metrics import CRITERIA_FIELDS, compute_criteria_table


# 角度フィッティングに最低限必要とみなす flow_direction のスパン [deg]
ANGLE_SPAN_MIN_DEG = 20.0
# センサ値を「ゼロ」とみなして無視するためのしきい値
ZERO_EPS = 1e-6
# diff_ratio 用: IQR によるロバストスケーリングの係数
DIFF_RATIO_IQR_K = 1.5
# 互換用プレースホルダ（古いコード片で参照されているが、実質的には未使用）
DIFF_RATIO_MIN_DEG = DIFF_RATIO_IQR_K


def _robust_group_max(s: pd.Series) -> float:
    """グループ内の値からロバストな最大値を計算するヘルパー。

    - NaN / 非有限値 / ゼロ付近 (<= ZERO_EPS) は無視する
    - IQR を用いて極端な外れ値の影響を抑えた最大値を返す
    """
    s = s[np.isfinite(s) & (s > ZERO_EPS)]
    if s.empty:
        return np.nan
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1
    if np.isfinite(iqr) and iqr > 0:
        thresh = q3 + DIFF_RATIO_IQR_K * iqr
        s = s[s <= thresh]
        if s.empty:
            return np.nan
    return float(s.max()) if not s.empty else np.nan


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Create 2D facet plots of front_in/front_out/rear_in/rear_out velocities "
            "from the merged CSV generated by csv_concat_4.py. "
            "flow_direction is treated as the probe angle in degrees (0=x axis, 90=y axis), "
            "from which |u_x|, |u_y|, and |u| are reconstructed."
        )
    )
    parser.add_argument(
        "--input",
        required=True,
        type=str,
        help="csv_concat_4.py が出力した結合CSVファイルのパス",
    )
    parser.add_argument(
        "--output",
        required=False,
        type=str,
        help="出力画像ファイルのパス（指定なしなら画面表示）",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=180,
        help="保存時の DPI（デフォルト: 180）",
    )
    parser.add_argument(
        "--style",
        type=str,
        default="whitegrid",
        help="seaborn のスタイル名（デフォルト: whitegrid）",
    )
    parser.add_argument(
        "--row-keys",
        nargs="*",
        default=["tilt_angle", "fold_angle"],
        help="Parameter names used to group rows (e.g., tilt_angle fold_angle)",
    )
    parser.add_argument(
        "--col-keys",
        nargs="*",
        default=["wall_spacing"],
        help="Parameter names used to group columns (e.g., wall_spacing)",
    )
    parser.add_argument(
        "--target-thrust",
        type=float,
        default=None,
        help="target_thrust value to plot (if omitted, the maximum value is used)",
    )
    parser.add_argument(
        "--single-angle-mode",
        type=str,
        choices=["nan", "use"],
        default="nan",
        help=(
            "How to treat points where all measurements share a single flow_direction angle: "
            "'nan' (default) skips them, 'use' assumes the flow is aligned with that angle and "
            "uses the mean magnitude."
        ),
    )
    parser.add_argument(
        "--mode",
        type=str,
        choices=[
            "scalar_mag",
            "scalar_norm",
            "scalar_norm_y",
            "vector_unsigned",
            "diff_fold",
            "diff_ratio",
            "diff_ratio_norm",
            "diff_ratio_y",
        ],
        default="vector_unsigned",
        help=(
            "Plot mode: "
            "scalar_mag = only |u| colormap, "
            "scalar_norm = |u| normalized by robust max per io, "
            "scalar_norm_y = |u| normalized by robust max per (io,y), "
            "vector_unsigned = |u| colormap with (signed) direction segments (default), "
            "diff_fold = |u_front| - |u_rear| with rear folded to front (|x|), "
            "diff_ratio = (front-rear)/mean(front,rear) per point, "
            "diff_ratio_norm = (front/robust_max - rear/robust_max) in %%, "
            "diff_ratio_y = diff_ratio_norm with robust max taken per (io,y)."
        ),
    )
    parser.add_argument(
        "--cmap-in",
        type=str,
        default="viridis",
        help="Colormap for in (upper) measurements when using scalar/vector modes (default: viridis).",
    )
    parser.add_argument(
        "--cmap-out",
        type=str,
        default="plasma",
        help="Colormap for out (lower) measurements when using scalar/vector modes (default: plasma).",
    )
    parser.add_argument(
        "--colorbar-mode",
        type=str,
        choices=["shared", "by_io"],
        default="by_io",
        help="Colorbar layout for scalar/vector modes: shared (one for all) or by_io (separate for in/out).",
    )
    parser.add_argument(
        "--export-components",
        type=str,
        default=None,
        help=(
            "If specified, exports reconstructed velocity components in long format (one row per "
            "point and sensor) to the given CSV path."
        ),
    )
    parser.add_argument(
        "--export-criteria",
        type=str,
        default=None,
        help="criteria.tex に基づく定量評価（facet×io×side 集計）を CSV として出力するパス",
    )
    parser.add_argument(
        "--print-criteria",
        action="store_true",
        help="criteria.tex に基づく定量評価（facet×io×side 集計）を標準出力に表示する",
    )
    parser.add_argument(
        "--annotate-criteria",
        action="store_true",
        help="プロットの各ファセットに定量評価（facet×io×side）を注記表示する",
    )
    parser.add_argument(
        "--criteria-field",
        type=str,
        choices=CRITERIA_FIELDS,
        default="uy",
        help=(
            "非対称指数(I_asym)と流束重心(X_center)に用いる各点の値。"
            "ux/uy/u と、その正規化（norm/norm_y）を選択できます。"
        ),
    )
    parser.add_argument(
        "--plot-xcenter",
        action="store_true",
        help="criteria の X_center を図中にマーカー（縦線）として重ね描きする",
    )
    parser.add_argument(
        "--plot-theta-def",
        action="store_true",
        help="criteria の theta_def を図中に矢印として重ね描きする",
    )
    parser.add_argument(
        "--criteria-by-y",
        action="store_true",
        help="X_center 等の criteria を y ごと（facet×io×side×y）に算出する（行数が増えます）",
    )
    return parser.parse_args()


def _safe_to_numeric(df: pd.DataFrame, cols):
    for c in cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    return df


def load_and_filter(input_path: Path, target_thrust: float | None) -> pd.DataFrame:
    """結合CSVを読み込み、target_thrust でフィルタし、keyword 平均を行った DataFrame を返す。"""
    try:
        df = pd.read_csv(input_path)
    except Exception as e:
        raise RuntimeError(f"CSV 読み込みに失敗しました: {e}")

    required_cols = [
        "flow_distance",
        "flow_height",
        "flow_direction",
        "front_in",
        "front_out",
        "rear_in",
        "rear_out",
        "target_thrust",
    ]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"必須列が不足しています: {', '.join(missing)}")

    # 数値化（必要列のみ）
    num_cols = [
        "flow_distance",
        "flow_height",
        "flow_direction",
        "front_in",
        "front_out",
        "rear_in",
        "rear_out",
        "target_thrust",
        "distance",
        "fold_angle",
        "height",
        "prop_spacing",
        "tilt_angle",
        "wall_spacing",
    ]
    df = _safe_to_numeric(df, num_cols)

    # target_thrust でフィルタ（指定なしなら最大値のみ）
    if df["target_thrust"].notna().sum() == 0:
        raise ValueError("target_thrust 列に有効な値がありません。")
    if target_thrust is None:
        th = df["target_thrust"].max()
        df = df[df["target_thrust"] == th].copy()
        print(f"target_thrust 未指定のため、最大値 {th} のみを使用します。")
    else:
        df = df[df["target_thrust"] == target_thrust].copy()
        if df.empty:
            raise ValueError(f"指定された target_thrust={target_thrust} に一致する行がありません。")

    # keyword の平均化：keyword 以外のパラメータでグループ化し、数値列は平均
    keyword_col = "keyword"
    if keyword_col in df.columns:
        # 数値列と非数値列を分ける
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        group_cols = [c for c in df.columns if c not in numeric_cols and c != keyword_col]
        if not group_cols:
            # 念のためのフォールバック：keyword だけ外して平均
            group_cols = [c for c in df.columns if c != keyword_col]
        df = (
            df.groupby(group_cols, dropna=False)
            .mean(numeric_only=True)
            .reset_index()
        )
        print("keyword 列を除いて数値列を平均化しました。")

    return df


def reconstruct_components(df: pd.DataFrame, single_angle_mode: str = "nan") -> pd.DataFrame:
    """flow_direction[deg] と各センサ値から |u_x|,|u_y|,|u| を再構成する。

    - 速度ベクトル u を大きさ U>=0, 角度 phi (向きなし、[0,pi) に制限) とみなし、
      各測定を m_i ≈ U * |cos(theta_i - phi)| として最小二乗フィットする。
    - theta_i は flow_direction[deg]、m_i は各センサ(front_in など)の値。
    - 各 (distance, flow_distance, flow_height, ..., target_thrust, センサ) ごとに
      (U, phi) を推定し、そこから |u_x|, |u_y| を計算する。
    """
    sensors = ["front_in", "front_out", "rear_in", "rear_out"]

    dfc = df.copy()

    # インデックスに使う基本パラメータ列
    base_index_cols_all = [
        "distance",
        "flow_distance",
        "flow_height",
        "fold_angle",
        "height",
        "prop_spacing",
        "tilt_angle",
        "wall_spacing",
        "target_thrust",
    ]
    base_index_cols = [c for c in base_index_cols_all if c in dfc.columns]
    if "flow_distance" not in base_index_cols or "flow_height" not in base_index_cols:
        raise ValueError("flow_distance および flow_height 列が必要です。")

    # phi 探索グリッド（0〜pi、1deg 刻み相当）
    phi_grid = np.linspace(0.0, np.pi, 180, endpoint=False)

    all_pivot = None

    for sensor in sensors:
        if sensor not in dfc.columns:
            continue

        cols = base_index_cols + ["flow_direction", sensor]
        tmp = dfc[cols].dropna(subset=["flow_direction", sensor]).copy()
        if tmp.empty:
            continue

        rows = []
        for keys, g in tmp.groupby(base_index_cols):
            m_raw = g[sensor].to_numpy(dtype=float)
            theta_raw_deg = g["flow_direction"].to_numpy(dtype=float)
            # センサごとに角度基準を補正（front を基準に、rear は反転）
            if sensor.startswith("rear"):
                theta_raw_deg = 180.0 - theta_raw_deg
            theta_raw = np.deg2rad(theta_raw_deg)
            if len(m_raw) < 1:
                continue

            # ゼロ（またはほぼゼロ）の測定値は無効として除外
            valid_mask = np.isfinite(m_raw) & (np.abs(m_raw) > ZERO_EPS) & np.isfinite(theta_raw)
            if not np.any(valid_mask):
                continue
            m = m_raw[valid_mask]
            theta = theta_raw[valid_mask]

            unique_theta = np.unique(theta)
            # 角度スパンが小さすぎるグループは、u ベクトルを安定に推定できないのでスキップ
            if unique_theta.size >= 2:
                angle_span_rad = float(unique_theta.max() - unique_theta.min())
                angle_span_deg = np.degrees(angle_span_rad)
                if angle_span_deg < ANGLE_SPAN_MIN_DEG:
                    continue
            # 角度が1種類しか無い場合の扱い
            if unique_theta.size == 1:
                if single_angle_mode == "nan":
                    # デフォルト: その点は捨てる
                    continue
                # 'use' モード: その角度方向に流れが向いていると仮定し、U は m の平均
                phi_best = float(unique_theta[0])
                U_best = float(np.nanmean(m))
                if not np.isfinite(U_best) or U_best < 0:
                    continue
            else:
                # 形状: (n_sample, n_phi)
                cos_diff = np.abs(np.cos(theta[:, None] - phi_grid[None, :]))
                denom = np.sum(cos_diff ** 2, axis=0)
                valid = denom > 1e-8
                if not np.any(valid):
                    continue

                num = np.sum(cos_diff * m[:, None], axis=0)
                U = np.zeros_like(phi_grid)
                U[valid] = num[valid] / denom[valid]

                pred = U[None, :] * cos_diff
                err = np.sum((pred - m[:, None]) ** 2, axis=0)
                err[~valid] = np.inf

                idx = int(np.argmin(err))
                phi_best = float(phi_grid[idx])
                U_best = float(U[idx])
                if not np.isfinite(U_best) or U_best < 0:
                    continue

            ux_abs = U_best * abs(np.cos(phi_best))
            uy_abs = U_best * abs(np.sin(phi_best))

            row = {col: val for col, val in zip(base_index_cols, keys)}
            row[f"{sensor}_ux_abs"] = ux_abs
            row[f"{sensor}_uy_abs"] = uy_abs
            row[f"{sensor}_mag"] = U_best
            # メタ情報: サンプル数と角度数（ゼロ除外後）
            row[f"{sensor}_n_samples"] = int(m.size)
            row[f"{sensor}_n_unique_angles"] = int(unique_theta.size)
            row[f"{sensor}_phi_deg"] = float(np.degrees(phi_best))
            rows.append(row)

        if not rows:
            continue

        pivot = pd.DataFrame(rows).set_index(base_index_cols)

        if all_pivot is None:
            all_pivot = pivot
        else:
            all_pivot = all_pivot.join(pivot, how="outer")

    if all_pivot is None or all_pivot.empty:
        raise ValueError("有効な flow_direction とセンサ値の組から再構成できるデータがありません。")

    return all_pivot.reset_index()


def build_long_with_coordinates(components_df: pd.DataFrame) -> pd.DataFrame:
    """センサごとの |u_x|,|u_y|,|u| から、(x,y) 付きのロング形式に変換する。"""
    sensors = ["front_in", "front_out", "rear_in", "rear_out"]

    # インデックス列: センサ由来の列（front_in_*, rear_out_* など）を除いたもの
    meas_prefixes = tuple(f"{s}_" for s in sensors)
    idx_cols = [c for c in components_df.columns if not c.startswith(meas_prefixes)]

    long_parts = []
    for sensor in sensors:
        ux_col = f"{sensor}_ux_abs"
        uy_col = f"{sensor}_uy_abs"
        mag_col = f"{sensor}_mag"
        meta_ns_col = f"{sensor}_n_samples"
        meta_na_col = f"{sensor}_n_unique_angles"
        meta_phi_col = f"{sensor}_phi_deg"
        use_cols = [
            c
            for c in [ux_col, uy_col, mag_col, meta_ns_col, meta_na_col, meta_phi_col]
            if c in components_df.columns
        ]
        if not use_cols:
            continue
        sub = components_df[idx_cols + use_cols].copy()
        # 少なくとも |u| が存在する行のみ使用（無い場合は両成分が揃っていないのでスキップ）
        if mag_col not in sub.columns:
            continue
        sub = sub.dropna(subset=[mag_col])
        if sub.empty:
            continue
        rename_map = {
            ux_col: "ux_abs",
            uy_col: "uy_abs",
            mag_col: "u_mag",
            meta_ns_col: "n_samples",
            meta_na_col: "n_unique_angles",
            meta_phi_col: "phi_deg",
        }
        sub = sub.rename(columns={k: v for k, v in rename_map.items() if k in sub.columns})
        sub["sensor"] = sensor
        long_parts.append(sub)

    if not long_parts:
        raise ValueError("有効な |u| データがありません。")

    df_long = pd.concat(long_parts, ignore_index=True)

    # 座標 (x, y) を計算
    if "flow_distance" not in df_long.columns or "flow_height" not in df_long.columns:
        raise ValueError("flow_distance, flow_height 列が必要です。")

    # flow_distance は [m] 相当なので、可視化では [mm] に変換して扱う
    df_long["flow_distance_mm"] = df_long["flow_distance"] * 1000.0

    def _side_from_sensor(s: str) -> str:
        return "front" if s.startswith("front") else "rear"

    def _io_from_sensor(s: str) -> str:
        return "in" if s.endswith("in") else "out"

    df_long["side"] = df_long["sensor"].apply(_side_from_sensor)
    df_long["io"] = df_long["sensor"].apply(_io_from_sensor)

    # x 座標: front=+flow_distance, rear=-flow_distance
    df_long["x"] = np.where(
        df_long["side"] == "rear",
        -df_long["flow_distance_mm"],
        df_long["flow_distance_mm"],
    )
    # y 座標: in=180-flow_height (上側), out=-flow_height (下側)
    df_long["y"] = np.where(
        df_long["io"] == "in",
        180.0 - df_long["flow_height"],
        -df_long["flow_height"],
    )

    # 符号付き成分も付与:
    # - x: front を +x, rear を -x
    # - y: 上を +y とし、流れは上→下と仮定して常に負方向
    df_long["ux"] = df_long["ux_abs"]
    df_long.loc[df_long["side"] == "rear", "ux"] = -df_long.loc[df_long["side"] == "rear", "ux_abs"]
    df_long["uy"] = -df_long["uy_abs"]

    return df_long


def export_components_long(
    components_df: pd.DataFrame,
    export_path: str,
    row_keys=None,
    col_keys=None,
) -> None:
    """reconstruct_components の出力をロング形式に変換して CSV にエクスポートする。

    1行 = 1つの (distance, flow_distance, flow_height, ..., sensor) に対応し、主な列は:
      - パラメータ列（distance, tilt_angle, ...）
      - sensor: 'front_in', 'front_out', 'rear_in', 'rear_out'
      - u_mag: 推定された |u|
      - ux_abs, uy_abs: 推定された |u_x|, |u_y|
      - ux, uy: front を +x、rear を -x とし、流れが上→下（-y）と仮定して付与した符号付き成分
      - diff_ratio_y_pct: diff_ratio_y と同じ定義の front/rear 差分[%]
          (row_facet, col_facet, io, y) ごとに front/rear をロバスト最大で正規化し、
          (front_norm_y - rear_norm_y) * 100 を各点に付与したもの。
      - phi_deg: 推定された角度（向きなし, [0, 180)）
      - n_samples: この点・センサでフィットに使われたデータ数（ゼロ除外後）
      - n_unique_angles: flow_direction のユニークな個数（ゼロ除外後）
    """
    sensors = ["front_in", "front_out", "rear_in", "rear_out"]
    meas_prefixes = tuple(f"{s}_" for s in sensors)
    idx_cols = [c for c in components_df.columns if not c.startswith(meas_prefixes)]

    long_rows: list[dict] = []
    for sensor in sensors:
        ux_col = f"{sensor}_ux_abs"
        uy_col = f"{sensor}_uy_abs"
        mag_col = f"{sensor}_mag"
        ns_col = f"{sensor}_n_samples"
        na_col = f"{sensor}_n_unique_angles"
        phi_col = f"{sensor}_phi_deg"
        cols = [c for c in [ux_col, uy_col, mag_col, ns_col, na_col, phi_col] if c in components_df.columns]
        if not cols:
            continue
        sub = components_df[idx_cols + cols].copy()
        sub = sub.dropna(subset=[mag_col])
        if sub.empty:
            continue
        for _, r in sub.iterrows():
            row = {k: r[k] for k in idx_cols}
            row["sensor"] = sensor
            ux_abs = r.get(ux_col, np.nan)
            uy_abs = r.get(uy_col, np.nan)
            row["ux_abs"] = ux_abs
            row["uy_abs"] = uy_abs
            row["u_mag"] = r.get(mag_col, np.nan)
            # front 側を +x, rear 側を -x とする符号付き Ux
            if isinstance(sensor, str) and sensor.startswith("rear"):
                row["ux"] = -float(ux_abs) if np.isfinite(ux_abs) else np.nan
            else:
                row["ux"] = float(ux_abs) if np.isfinite(ux_abs) else np.nan
            # 流れは上→下と仮定し、y 正方向を上とすると Uy は常に負
            row["uy"] = -float(uy_abs) if np.isfinite(uy_abs) else np.nan
            row["n_samples"] = int(r.get(ns_col, np.nan)) if ns_col in cols else np.nan
            row["n_unique_angles"] = int(r.get(na_col, np.nan)) if na_col in cols else np.nan
            row["phi_deg"] = r.get(phi_col, np.nan) if phi_col in cols else np.nan
            long_rows.append(row)

    if not long_rows:
        raise ValueError("export_components_long: no valid rows to export.")

    df_export = pd.DataFrame(long_rows)

    # diff_ratio_y と同じ % を、通常エクスポートに追加する
    # - plot_facet_diff_ratio_y() と同じ定義で計算する（ファセット内の (io, y) ごとに正規化）
    # - 計算に必要な列が不足している場合は NaN を出力し、警告を出す
    df_export["diff_ratio_y_pct"] = np.nan
    try:
        tmp = add_facet_labels(df_export.copy(), row_keys, col_keys)

        # merge 後の suffix 衝突を避ける（df_export 側に diff_ratio_y_pct が既にあるため）
        tmp = tmp.drop(columns=["diff_ratio_y_pct"], errors="ignore")

        # センサ名から side/io を付与
        tmp["side"] = np.where(tmp["sensor"].astype(str).str.startswith("front"), "front", "rear")
        tmp["io"] = np.where(tmp["sensor"].astype(str).str.endswith("in"), "in", "out")

        if "flow_distance" not in tmp.columns or "flow_height" not in tmp.columns:
            raise ValueError("flow_distance/flow_height 列がありません。")

        # plot と同じ座標変換（x は mm）
        tmp["flow_distance_mm"] = pd.to_numeric(tmp["flow_distance"], errors="coerce") * 1000.0
        tmp["x"] = np.where(tmp["side"] == "rear", -tmp["flow_distance_mm"], tmp["flow_distance_mm"])
        fh = pd.to_numeric(tmp["flow_height"], errors="coerce")
        tmp["y"] = np.where(tmp["io"] == "in", 180.0 - fh, -fh)

        # front/rear を |x| で折り返してペアリングし、diff_ratio_y を計算
        diff_df = compute_front_rear_diff_fold(tmp)
        group_keys = ["row_facet", "col_facet", "io", "y"]
        front_max = diff_df.groupby(group_keys)["front"].transform(_robust_group_max)
        rear_max = diff_df.groupby(group_keys)["rear"].transform(_robust_group_max)

        diff_df = diff_df.copy()
        with np.errstate(divide="ignore", invalid="ignore"):
            diff_df["front_norm_y"] = np.where(
                np.isfinite(front_max) & (front_max > 0),
                diff_df["front"] / front_max,
                np.nan,
            )
            diff_df["rear_norm_y"] = np.where(
                np.isfinite(rear_max) & (rear_max > 0),
                diff_df["rear"] / rear_max,
                np.nan,
            )
        diff_df["diff_ratio_y_pct"] = (diff_df["front_norm_y"] - diff_df["rear_norm_y"]) * 100.0

        # 各センサ行へ付与（内部キーとして row/col facet を使用。出力列には追加しない）
        tmp["x_abs"] = tmp["x"].abs()
        key_cols = ["row_facet", "col_facet", "io", "x_abs", "y"]
        diff_key = diff_df[key_cols + ["diff_ratio_y_pct"]].copy()
        tmp2 = tmp.merge(diff_key, on=key_cols, how="left")
        df_export["diff_ratio_y_pct"] = tmp2["diff_ratio_y_pct"].to_numpy()
    except Exception as e:
        print(f"Warning: diff_ratio_y_pct の計算に失敗したため NaN を出力します: {e}")

    out_path = Path(export_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df_export.to_csv(out_path, index=False)
    print(f"Exported reconstructed components (long format) to: {out_path}")


def _format_val(v):
    if pd.isna(v):
        return "nan"
    if isinstance(v, (int, np.integer)):
        return f"{int(v)}"
    try:
        fv = float(v)
        # 角度や距離は整数 or 簡易表記で十分
        if abs(fv - round(fv)) < 1e-6:
            return f"{int(round(fv))}"
        return f"{fv:g}"
    except Exception:
        return str(v)


def add_facet_labels(df_long: pd.DataFrame, row_keys, col_keys) -> pd.DataFrame:
    """行・列ファセット用のラベル列を追加する。"""
    row_keys = [k for k in (row_keys or []) if k in df_long.columns]
    col_keys = [k for k in (col_keys or []) if k in df_long.columns]

    if not row_keys:
        df_long["row_facet"] = "all"
    else:
        def _row_label(r):
            vals = []
            for k in row_keys:
                val = _format_val(r[k])
                if k == "tilt_angle":
                    vals.append(f"θ={val}°")
                elif k == "fold_angle":
                    vals.append(f"Φ={val}°")
                else:
                    vals.append(f"{k}={val}")
            # multi-line label (Excel-like row header)
            return "\n".join(vals)

        df_long["row_facet"] = df_long.apply(_row_label, axis=1)

    if not col_keys:
        df_long["col_facet"] = "all"
    else:
        def _col_label(r):
            vals = []
            for k in col_keys:
                val = _format_val(r[k])
                if k == "wall_spacing":
                    vals.append(f"W={val}")
                else:
                    vals.append(f"{k}={val}")
            return ", ".join(vals)

        df_long["col_facet"] = df_long.apply(_col_label, axis=1)

    return df_long


def _format_num(v: float | int | None, fmt: str) -> str:
    if v is None:
        return "nan"
    try:
        fv = float(v)
    except Exception:
        return "nan"
    if not np.isfinite(fv):
        return "nan"
    return format(fv, fmt)


def _annotate_criteria_on_facet_axes(
    axes: np.ndarray,
    row_levels: list[str],
    col_levels: list[str],
    criteria_df: pd.DataFrame,
) -> None:
    """各ファセットに criteria 集計結果（facet×io×side）を注記する。"""
    need_cols = [
        "row_facet",
        "col_facet",
        "io",
        "side",
        "criteria_field",
        "I_asym",
        "X_center_mm",
        "theta_def_deg",
    ]
    miss = [c for c in need_cols if c not in criteria_df.columns]
    if miss:
        raise ValueError(f"criteria_df に必要な列が不足しています: {', '.join(miss)}")

    # 1 facet = (row_facet, col_facet) 内に、io×side の4行をまとめて書く
    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            if not ax.get_visible():
                continue

            sub = criteria_df[
                (criteria_df["row_facet"] == rlab) & (criteria_df["col_facet"] == clab)
            ]
            if sub.empty:
                continue

            # criteria_field は facet 内で同一のはず
            cf = str(sub["criteria_field"].iloc[0])
            lines = [f"criteria={cf}"]
            for io in ["in", "out"]:
                for side in ["front", "rear"]:
                    one = sub[(sub["io"] == io) & (sub["side"] == side)]
                    if one.empty:
                        lines.append(f"{io}/{side}: -")
                        continue
                    # criteria_by_y の場合は y 方向に平均した代表値を表示
                    r = one.agg(
                        {
                            "I_asym": "mean",
                            "X_center_mm": "mean",
                            "theta_def_deg": "mean",
                        }
                    )
                    I = _format_num(r.get("I_asym", np.nan), ".3g")
                    X = _format_num(r.get("X_center_mm", np.nan), ".3g")
                    th = _format_num(r.get("theta_def_deg", np.nan), ".3g")
                    lines.append(f"{io}/{side}: I={I}, X={X}mm, θ={th}°")

            txt = "\n".join(lines)
            ax.text(
                0.02,
                0.98,
                txt,
                transform=ax.transAxes,
                ha="left",
                va="top",
                fontsize=8.5,
                color="white",
                bbox=dict(facecolor="black", alpha=0.35, edgecolor="none", pad=2.0),
                zorder=10,
            )


def _overlay_criteria_marks_on_facet_axes(
    axes: np.ndarray,
    row_levels: list[str],
    col_levels: list[str],
    criteria_df: pd.DataFrame,
    *,
    plot_xcenter: bool,
    plot_theta_def: bool,
    x_is_abs: bool,
) -> None:
    """各ファセットに X_center / theta_def の図示（マーカー/矢印）を重ね描きする。"""
    if (not plot_xcenter) and (not plot_theta_def):
        return

    need_cols = ["row_facet", "col_facet", "io", "side", "X_center_mm", "theta_def_deg"]
    miss = [c for c in need_cols if c not in criteria_df.columns]
    if miss:
        raise ValueError(f"criteria_df に必要な列が不足しています: {', '.join(miss)}")

    # 表示スタイル（ioで色、sideで線種/マーカー）
    io_color = {"in": "#2ca02c", "out": "#9467bd"}  # green / purple
    side_ls = {"front": "-", "rear": "--"}

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            if not ax.get_visible():
                continue

            sub = criteria_df[
                (criteria_df["row_facet"] == rlab) & (criteria_df["col_facet"] == clab)
            ]
            if sub.empty:
                continue

            x0, x1 = ax.get_xlim()
            y0, y1 = ax.get_ylim()
            x_span = x1 - x0 if np.isfinite(x1 - x0) and x1 != x0 else 1.0
            y_span = y1 - y0 if np.isfinite(y1 - y0) and y1 != y0 else 1.0

            # in/out で上下に分けて表示（データ座標）
            y_anchor = {"in": y1 - 0.08 * y_span, "out": y0 + 0.08 * y_span}

            # 矢印の長さ（データ座標でスケール）
            L = 0.12 * min(abs(x_span), abs(y_span))

            for io in ["in", "out"]:
                for side in ["front", "rear"]:
                    one = sub[(sub["io"] == io) & (sub["side"] == side)]
                    if one.empty:
                        continue
                    col = io_color.get(io, "white")
                    ls = side_ls.get(side, "-")

                    # criteria_by_y: y 列がある場合は、y ごとの X_center を線/点列で表示
                    has_y = "y" in one.columns
                    if plot_xcenter and has_y and len(one) > 1:
                        xs = pd.to_numeric(one["X_center_mm"], errors="coerce").to_numpy(dtype=float)
                        ys = pd.to_numeric(one["y"], errors="coerce").to_numpy(dtype=float)
                        m = np.isfinite(xs) & np.isfinite(ys)
                        if np.any(m):
                            xs = xs[m]
                            ys = ys[m]
                            order = np.argsort(ys)
                            xs = xs[order]
                            ys = ys[order]
                            xplot = np.abs(xs) if x_is_abs else xs
                            ax.plot(
                                xplot,
                                ys,
                                color=col,
                                linestyle=ls,
                                linewidth=1.6,
                                marker="o",
                                markersize=3.0,
                                alpha=0.9,
                                zorder=9,
                            )
                    else:
                        # 従来: 代表値で 1 点だけ
                        r = one.agg({"X_center_mm": "mean", "theta_def_deg": "mean"})
                        xc_mm = r.get("X_center_mm", np.nan)
                        th_deg = r.get("theta_def_deg", np.nan)
                        if not np.isfinite(xc_mm):
                            continue
                        x_plot = abs(float(xc_mm)) if x_is_abs else float(xc_mm)
                        if not (min(x0, x1) - 0.05 * x_span <= x_plot <= max(x0, x1) + 0.05 * x_span):
                            continue
                        yy = y_anchor[io]
                        if plot_xcenter:
                            ax.plot(
                                [x_plot, x_plot],
                                [yy - 0.03 * y_span, yy + 0.03 * y_span],
                                color=col,
                                linestyle=ls,
                                linewidth=2.0,
                                alpha=0.95,
                                zorder=9,
                            )
                        if plot_theta_def and np.isfinite(th_deg):
                            th = np.deg2rad(float(th_deg))
                            dx_out = L * np.sin(th)
                            dy = -L * np.cos(th)
                            sign_x = 1.0 if side == "front" else -1.0
                            dx = dx_out * sign_x
                            if x_is_abs:
                                dx = abs(dx)
                            ax.annotate(
                                "",
                                xy=(x_plot + dx, yy + dy),
                                xytext=(x_plot, yy),
                                arrowprops=dict(
                                    arrowstyle="-|>",
                                    color=col,
                                    linewidth=1.6,
                                    linestyle=ls,
                                    alpha=0.95,
                                    shrinkA=0,
                                    shrinkB=0,
                                ),
                                zorder=9,
                            )


def plot_facet_2d(
    df_long: pd.DataFrame,
    mode: str,
    dpi: int,
    output: str | None,
    cmap_in: str = "viridis",
    cmap_out: str = "plasma",
    colorbar_mode: str = "by_io",
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """(x,y,|u|) をファセットプロットする。mode='vector_unsigned' の場合は無向きベクトルも重ねる。"""
    if df_long.empty:
        raise ValueError("プロット対象データが空です。")

    row_levels = sorted(df_long["row_facet"].unique().tolist())
    col_levels = sorted(df_long["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    # 軸範囲とベクトルスケールのための全体統計
    x_min = float(df_long["x"].min())
    x_max = float(df_long["x"].max())
    y_min = float(df_long["y"].min())
    y_max = float(df_long["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0
    base_len = 0.15 * min(x_span, y_span)

    # カラーマップ用のスケール（shared/by_io 切替）
    if colorbar_mode == "by_io":
        in_mask = df_long["io"] == "in"
        out_mask = df_long["io"] == "out"
        if in_mask.any():
            u_min_in = float(df_long.loc[in_mask, "u_mag"].min())
            u_max_in = float(df_long.loc[in_mask, "u_mag"].max())
        else:
            u_min_in = u_max_in = 0.0
        if out_mask.any():
            u_min_out = float(df_long.loc[out_mask, "u_mag"].min())
            u_max_out = float(df_long.loc[out_mask, "u_mag"].max())
        else:
            u_min_out = u_max_out = 0.0
        # director ベクトルの長さスケール用に、全体での最大値も保持しておく
        u_max = max(u_max_in, u_max_out)
        if not np.isfinite(u_max) or u_max <= 0:
            raise ValueError("|u| の有効な値がありません。")
        u_min = 0.0
    else:
        u_min = float(df_long["u_mag"].min())
        u_max = float(df_long["u_mag"].max())
        if not np.isfinite(u_max) or u_max <= 0:
            raise ValueError("|u| の有効な値がありません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    # colormap 用に最後に使った scatter を保持（shared/by_io で別々に管理）
    last_scatter_shared = None
    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = df_long[(df_long["row_facet"] == rlab) & (df_long["col_facet"] == clab)]
            if sub.empty:
                ax.set_visible(False)
                continue

            if colorbar_mode == "by_io":
                # in/out それぞれ別カラーマップ・スケールで描画
                sub_in = sub[sub["io"] == "in"]
                if not sub_in.empty and u_max_in > 0:
                    sc_in = ax.scatter(
                        sub_in["x"],
                        sub_in["y"],
                        c=sub_in["u_mag"],
                        cmap=cmap_in,
                        vmin=u_min_in,
                        vmax=u_max_in,
                        s=60,
                        edgecolors="none",
                        zorder=3,
                    )
                    last_scatter_in = sc_in
                sub_out = sub[sub["io"] == "out"]
                if not sub_out.empty and u_max_out > 0:
                    sc_out = ax.scatter(
                        sub_out["x"],
                        sub_out["y"],
                        c=sub_out["u_mag"],
                        cmap=cmap_out,
                        vmin=u_min_out,
                        vmax=u_max_out,
                        s=60,
                        edgecolors="none",
                        zorder=3,
                    )
                    last_scatter_out = sc_out
            else:
                sc = ax.scatter(
                    sub["x"],
                    sub["y"],
                    c=sub["u_mag"],
                    cmap=cmap_out,
                    vmin=u_min,
                    vmax=u_max,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_shared = sc

            if mode == "vector_unsigned":
                # ベクトル場を線分として重ねる（符号付き ux, uy が存在すればそれを使用）
                if "ux" in sub.columns and "uy" in sub.columns:
                    sub_vec = sub.dropna(subset=["ux", "uy", "u_mag"])
                    use_abs = False
                else:
                    # 後方互換用（古いCSVなど）
                    sub_vec = sub.dropna(subset=["ux_abs", "uy_abs", "u_mag"])
                    use_abs = True
                for _, row in sub_vec.iterrows():
                    if use_abs:
                        ux = float(row["ux_abs"])
                        uy = float(row["uy_abs"])
                    else:
                        ux = float(row["ux"])
                        uy = float(row["uy"])
                    um = float(row["u_mag"])
                    if um <= 0:
                        continue
                    dx = ux / um
                    dy = uy / um
                    L = base_len * (um / u_max)
                    x0 = row["x"] - 0.5 * L * dx
                    x1 = row["x"] + 0.5 * L * dx
                    y0 = row["y"] - 0.5 * L * dy
                    y1 = row["y"] + 0.5 * L * dy
                    ax.plot(
                        [x0, x1],
                        [y0, y1],
                        color="white",
                        linewidth=0.7,
                        alpha=0.9,
                        zorder=4,
                    )

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (front=+, rear=-)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            # facet titles are handled outside the axes
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=False,
        )

    # adjust margins so that row/column labelsとカラーバーが収まるようにする
    # 左に十分な余白を確保（行ラベル用）、右はカラーバー用
    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)

    # place facet labels outside the axes like Excel (row labels on the left, column labels on top)
    fig.canvas.draw()  # ensure positions are updated
    # column labels (top)
    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        # fix y-position so it does not collide with the colorbar
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)
    # row labels (left) — axes 座標系で描画し、y 軸ラベルよりも外側に置く
    # これにより「row label -> y-axis label -> plot」の順になる
    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        # x をさらに左 (-0.75) にして、フォントサイズも他と揃えて少し大きく
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    if colorbar_mode == "by_io":
        # in/out 用に上下2本のカラーバーを配置
        if last_scatter_in is not None:
            cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
            cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
            cbar_in.set_label("|u| in [m/s]")
        if last_scatter_out is not None:
            cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
            cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
            cbar_out.set_label("|u| out [m/s]")
    else:
        if last_scatter_shared is not None:
            # single shared colorbar
            cax = fig.add_axes([0.86, 0.18, 0.02, 0.64])
            cbar = fig.colorbar(last_scatter_shared, cax=cax, orientation="vertical")
            cbar.set_label("|u| [m/s] (reconstructed magnitude)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


    # legacy helper _robust_group_max はモジュール先頭の実装に置き換え済み
    # ここにあった旧定義は削除しました（DIFF_R 参照などは使用されません）
def plot_facet_scalar_norm(df_long: pd.DataFrame, dpi: int, output: str | None):
    """|u| を in/out 別のロバスト最大値で正規化し、0〜100% のスカラー場として表示するモード。"""
    if df_long.empty:
        raise ValueError("プロット対象データが空です。")

    row_levels = sorted(df_long["row_facet"].unique().tolist())
    col_levels = sorted(df_long["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(df_long["x"].min())
    x_max = float(df_long["x"].max())
    y_min = float(df_long["y"].min())
    y_max = float(df_long["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    in_mask = df_long["io"] == "in"
    out_mask = df_long["io"] == "out"

    def _robust_max(vals: pd.Series) -> float | None:
        vals = vals.dropna()
        if vals.empty:
            return None
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            cand = q3 + DIFF_RATIO_IQR_K * iqr
            mx = float(vals.max())
            m = float(min(mx, cand))
        else:
            m = float(vals.max())
        if not np.isfinite(m) or m <= 0:
            return None
        return m

    umax_in = _robust_max(df_long.loc[in_mask, "u_mag"]) if in_mask.any() else None
    umax_out = _robust_max(df_long.loc[out_mask, "u_mag"]) if out_mask.any() else None

    if umax_in is None and umax_out is None:
        raise ValueError("scalar_norm 用のロバスト最大値が計算できません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = df_long[(df_long["row_facet"] == rlab) & (df_long["col_facet"] == clab)]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[sub["io"] == "in"]
            if umax_in is not None and not sub_in.empty:
                vals = (sub_in["u_mag"] / umax_in) * 100.0
                sc_in = ax.scatter(
                    sub_in["x"],
                    sub_in["y"],
                    c=vals,
                    cmap="viridis",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_in = sc_in

            sub_out = sub[sub["io"] == "out"]
            if umax_out is not None and not sub_out.empty:
                vals = (sub_out["u_mag"] / umax_out) * 100.0
                sc_out = ax.scatter(
                    sub_out["x"],
                    sub_out["y"],
                    c=vals,
                    cmap="plasma",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (front=+, rear=-)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    # in/out 用に上下2本のカラーバー（|u| 正規化用）
    if last_scatter_in is not None and umax_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("|u| norm [%] (in)")
    if last_scatter_out is not None and umax_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("|u| norm [%] (out)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def plot_facet_scalar_norm_y(
    df_long: pd.DataFrame,
    dpi: int,
    output: str | None,
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """|u| を (io, y) ごとのロバスト最大値で正規化し、0〜100% として表示するモード。"""
    if df_long.empty:
        raise ValueError("プロット対象データが空です。")

    df_norm = df_long.copy()
    # (io, y) ごとのロバスト最大値
    group_keys = ["io", "y"]
    umax_group = df_norm.groupby(group_keys)["u_mag"].transform(_robust_group_max)
    with np.errstate(divide="ignore", invalid="ignore"):
        df_norm["u_norm_y"] = np.where(
            np.isfinite(umax_group) & (umax_group > 0),
            df_norm["u_mag"] / umax_group * 100.0,
            np.nan,
        )

    row_levels = sorted(df_norm["row_facet"].unique().tolist())
    col_levels = sorted(df_norm["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(df_norm["x"].min())
    x_max = float(df_norm["x"].max())
    y_min = float(df_norm["y"].min())
    y_max = float(df_norm["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = df_norm[
                (df_norm["row_facet"] == rlab)
                & (df_norm["col_facet"] == clab)
            ]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[sub["io"] == "in"]
            if not sub_in.empty:
                sc_in = ax.scatter(
                    sub_in["x"],
                    sub_in["y"],
                    c=sub_in["u_norm_y"],
                    cmap="viridis",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_in = sc_in

            sub_out = sub[sub["io"] == "out"]
            if not sub_out.empty:
                sc_out = ax.scatter(
                    sub_out["x"],
                    sub_out["y"],
                    c=sub_out["u_norm_y"],
                    cmap="plasma",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (front=+, rear=-)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=False,
        )

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    if last_scatter_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("|u| norm_y [%] (in, per y)")
    if last_scatter_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("|u| norm_y [%] (out, per y)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def compute_front_rear_diff_fold(df_long: pd.DataFrame) -> pd.DataFrame:
    """front/rear を |x| で折り返し、|u_front| - |u_rear| を計算したテーブルを返す。"""
    if "side" not in df_long.columns:
        raise ValueError("df_long に 'side' 列がありません。")
    if "io" not in df_long.columns:
        raise ValueError("df_long に 'io' 列がありません。")

    dfw = df_long.copy()
    dfw["x_abs"] = dfw["x"].abs()

    index_cols = ["row_facet", "col_facet", "io", "x_abs", "y"]
    for c in index_cols:
        if c not in dfw.columns:
            raise ValueError(f"df_long に '{c}' 列がありません。")

    pivot = (
        dfw.pivot_table(
            index=index_cols,
            columns="side",
            values="u_mag",
            aggfunc="mean",
        )
        .reset_index()
    )
    if "front" not in pivot.columns or "rear" not in pivot.columns:
        raise ValueError("front/rear の両方のデータが不足しており、diff_fold を計算できません。")

    pivot = pivot.dropna(subset=["front", "rear"]).copy()
    if pivot.empty:
        raise ValueError("front/rear の両方が揃った点がありません。")

    pivot["diff"] = pivot["front"] - pivot["rear"]
    return pivot


def plot_facet_diff_fold(
    df_long: pd.DataFrame,
    dpi: int,
    output: str | None,
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """rear を front 側に折り返し、|u_front| - |u_rear| を色で表示するファセットプロット。"""
    diff_df = compute_front_rear_diff_fold(df_long)

    row_levels = sorted(diff_df["row_facet"].unique().tolist())
    col_levels = sorted(diff_df["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(diff_df["x_abs"].min())
    x_max = float(diff_df["x_abs"].max())
    y_min = float(diff_df["y"].min())
    y_max = float(diff_df["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    # in/out で差分スケールを分ける（見やすさのため）
    in_mask = diff_df["io"] == "in"
    out_mask = diff_df["io"] == "out"
    dmax_in = float(np.nanmax(np.abs(diff_df.loc[in_mask, "diff"]))) if in_mask.any() else 0.0
    dmax_out = float(np.nanmax(np.abs(diff_df.loc[out_mask, "diff"]))) if out_mask.any() else 0.0
    if (not np.isfinite(dmax_in) or dmax_in <= 0) and (not np.isfinite(dmax_out) or dmax_out <= 0):
        raise ValueError("diff_fold の有効な差分値がありません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = diff_df[
                (diff_df["row_facet"] == rlab)
                & (diff_df["col_facet"] == clab)
            ]
            if sub.empty:
                ax.set_visible(False)
                continue

            # in/out を別々のスケールで描画
            sub_in = sub[sub["io"] == "in"]
            if not sub_in.empty and dmax_in > 0:
                sc_in = ax.scatter(
                    sub_in["x_abs"],
                    sub_in["y"],
                    c=sub_in["diff"],
                    cmap="coolwarm",
                    vmin=-dmax_in,
                    vmax=dmax_in,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_in = sc_in
            sub_out = sub[sub["io"] == "out"]
            if not sub_out.empty and dmax_out > 0:
                sc_out = ax.scatter(
                    sub_out["x_abs"],
                    sub_out["y"],
                    c=sub_out["diff"],
                    cmap="coolwarm",
                    vmin=-dmax_out,
                    vmax=dmax_out,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (|x|, front/rear folded)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=True,
        )

    # layout and facet labels (row/column) – 同じスタイルを再利用
    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    # in/out 用に上下2本のカラーバー（diff用）
    if last_scatter_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("|u_front| - |u_rear| [m/s] (in)")
    if last_scatter_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("|u_front| - |u_rear| [m/s] (out)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def plot_facet_scalar_norm_y(df_long: pd.DataFrame, dpi: int, output: str | None):
    """|u| を (io, y) ごとのロバスト最大値で正規化し、%で表示するファセットプロット。"""
    if df_long.empty:
        raise ValueError("プロット対象データが空です。")
    if "flow_height" not in df_long.columns:
        raise ValueError("flow_height 列が必要です。")

    row_levels = sorted(df_long["row_facet"].unique().tolist())
    col_levels = sorted(df_long["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(df_long["x"].min())
    x_max = float(df_long["x"].max())
    y_min = float(df_long["y"].min())
    y_max = float(df_long["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    def _robust_max(vals: pd.Series) -> float:
        vals = vals.dropna()
        if vals.empty:
            return 0.0
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            L = q1 - DIFF_RATIO_MIN_DEG * iqr if False else 0  # placeholder
        # reuse global ZERO_EPS and ANGLE_SPAN_MIN_DEG not needed here
        # simpler: clamp to max
        return float(vals.max())

    # (io, flow_height) ごとのロバスト最大値
    def _group_robust_max(group: pd.Series) -> float:
        v = group.dropna()
        if v.empty:
            return 0.0
        q1 = v.quantile(0.25)
        q3 = v.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            cand = q3 + DIFF_RATIO_MIN_DEG * iqr if False else q3 + DIFF_RATIO_MIN_DEG * 0  # placeholder
        return float(v.max())

    # 実際には簡単に: IQRベースだが上限を max でクリップ
    def _robust_max_simple(v: pd.Series) -> float:
        v = v.dropna()
        if v.empty:
            return 0.0
        q1 = v.quantile(0.25)
        q3 = v.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            cand = q3 + DIFF_RATIO_MIN_DEG * 0  # no-op, keep for future tuning
        return float(v.max())

    # ここでは IQR 係数を使ったシンプル版
    def _robust_max_iqr(v: pd.Series) -> float:
        v = v.dropna()
        if v.empty:
            return 0.0
        q1 = v.quantile(0.25)
        q3 = v.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            cand = q3 + DIFF_RATIO_MIN_DEG * iqr
            return float(min(v.max(), cand))
        return float(v.max())

    df = df_long.copy()
    # 各パネル(row_facet, col_facet) 内の (io, flow_height) ごとにロバスト最大値を計算
    df["u_max_y"] = df.groupby(
        ["row_facet", "col_facet", "io", "flow_height"]
    )["u_mag"].transform(_robust_max_iqr)
    valid = df["u_max_y"] > ZERO_EPS
    df["u_norm_y"] = np.nan
    df.loc[valid, "u_norm_y"] = df.loc[valid, "u_mag"] / df.loc[valid, "u_max_y"] * 100.0

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = df[(df["row_facet"] == rlab) & (df["col_facet"] == clab)]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[(sub["io"] == "in") & sub["u_norm_y"].notna()]
            if not sub_in.empty:
                sc_in = ax.scatter(
                    sub_in["x"],
                    sub_in["y"],
                    c=sub_in["u_norm_y"],
                    cmap="viridis",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_in = sc_in

            sub_out = sub[(sub["io"] == "out") & sub["u_norm_y"].notna()]
            if not sub_out.empty:
                sc_out = ax.scatter(
                    sub_out["x"],
                    sub_out["y"],
                    c=sub_out["u_norm_y"],
                    cmap="plasma",
                    vmin=0.0,
                    vmax=100.0,
                    s=60,
                    edgecolors="none",
                    zorder=3,
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (front=+, rear=-)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    if last_scatter_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("|u| norm_y [%] (in)")
    if last_scatter_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("|u| norm_y [%] (out)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def plot_facet_diff_ratio(
    df_long: pd.DataFrame,
    dpi: int,
    output: str | None,
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """rear を front 側に折り返し、(front - rear) / mean(front, rear) を割合で表示するファセットプロット。"""
    diff_df = compute_front_rear_diff_fold(df_long)

    row_levels = sorted(diff_df["row_facet"].unique().tolist())
    col_levels = sorted(diff_df["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(diff_df["x_abs"].min())
    x_max = float(diff_df["x_abs"].max())
    y_min = float(diff_df["y"].min())
    y_max = float(diff_df["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    # 各点ごとに割合 r = (front - rear) / mean(front, rear) を計算（%単位）
    denom = 0.5 * (diff_df["front"] + diff_df["rear"])
    valid = denom.abs() > ZERO_EPS
    diff_df = diff_df.copy()
    diff_df["ratio"] = np.nan
    diff_df.loc[valid, "ratio"] = (diff_df.loc[valid, "diff"] / denom.loc[valid]) * 100.0

    # in/out 別に IQR ベースのロバストスケーリングでカラーバー範囲を決定
    in_mask = diff_df["io"] == "in"
    out_mask = diff_df["io"] == "out"

    def _compute_limits(mask: pd.Series) -> tuple[float, float] | tuple[None, None]:
        vals = diff_df.loc[mask, "ratio"].dropna()
        if vals.empty:
            return None, None
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            L = q1 - DIFF_RATIO_IQR_K * iqr
            U = q3 + DIFF_RATIO_IQR_K * iqr
        else:
            L, U = float(vals.min()), float(vals.max())
        lim = max(abs(L), abs(U))
        if not np.isfinite(lim) or lim == 0:
            lim = max(abs(float(vals.min())), abs(float(vals.max())))
        if not np.isfinite(lim) or lim == 0:
            return None, None
        return -lim, lim

    vmin_in, vmax_in = _compute_limits(in_mask)
    vmin_out, vmax_out = _compute_limits(out_mask)

    if vmin_in is None and vmin_out is None:
        raise ValueError("diff_ratio の有効な割合データがありません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = diff_df[
                (diff_df["row_facet"] == rlab)
                & (diff_df["col_facet"] == clab)
            ]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[sub["io"] == "in"]
            if vmin_in is not None and not sub_in.empty:
                sc_in = ax.scatter(
                    sub_in["x_abs"],
                    sub_in["y"],
                    c=sub_in["ratio"],
                    cmap="coolwarm",
                    vmin=vmin_in,
                    vmax=vmax_in,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_in = sc_in

            sub_out = sub[sub["io"] == "out"]
            if vmin_out is not None and not sub_out.empty:
                sc_out = ax.scatter(
                    sub_out["x_abs"],
                    sub_out["y"],
                    c=sub_out["ratio"],
                    cmap="coolwarm",
                    vmin=vmin_out,
                    vmax=vmax_out,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (|x|, front/rear folded)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=True,
        )

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    # in/out 用に上下2本のカラーバー（割合用）
    if last_scatter_in is not None and vmin_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("diff ratio [%] (in)")
    if last_scatter_out is not None and vmin_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("diff ratio [%] (out)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def plot_facet_diff_ratio_norm(
    df_long: pd.DataFrame,
    dpi: int,
    output: str | None,
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """front/rear を |x| で折り返し、各点ごとに
       r = (front/front_max_robust - rear/rear_max_robust) * 100 [%]
       をプロットするモード。

    front_max_robust, rear_max_robust は in/out 別に IQR ベースでロバストに決定する。
    """
    diff_df = compute_front_rear_diff_fold(df_long)

    row_levels = sorted(diff_df["row_facet"].unique().tolist())
    col_levels = sorted(diff_df["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(diff_df["x_abs"].min())
    x_max = float(diff_df["x_abs"].max())
    y_min = float(diff_df["y"].min())
    y_max = float(diff_df["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    # in/out 別に front/rear のロバスト最大値を計算
    in_mask = diff_df["io"] == "in"
    out_mask = diff_df["io"] == "out"

    def _robust_max(vals: pd.Series) -> float | None:
        vals = vals.dropna()
        if vals.empty:
            return None
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            cand = q3 + DIFF_RATIO_IQR_K * iqr
            mx = float(vals.max())
            m = float(min(mx, cand))
        else:
            m = float(vals.max())
        if not np.isfinite(m) or m <= 0:
            return None
        return m

    front_max_in = _robust_max(diff_df.loc[in_mask, "front"]) if in_mask.any() else None
    rear_max_in = _robust_max(diff_df.loc[in_mask, "rear"]) if in_mask.any() else None
    front_max_out = _robust_max(diff_df.loc[out_mask, "front"]) if out_mask.any() else None
    rear_max_out = _robust_max(diff_df.loc[out_mask, "rear"]) if out_mask.any() else None

    if all(m is None for m in [front_max_in, rear_max_in, front_max_out, rear_max_out]):
        raise ValueError("diff_ratio_norm 用のロバスト最大値が計算できません。")

    diff_df = diff_df.copy()
    diff_df["ratio_norm"] = np.nan

    # in 側
    if in_mask.any() and front_max_in and rear_max_in:
        sub = diff_df.loc[in_mask].copy()
        f_norm = sub["front"] / front_max_in
        r_norm = sub["rear"] / rear_max_in
        diff_df.loc[in_mask, "ratio_norm"] = (f_norm - r_norm) * 100.0

    # out 側
    if out_mask.any() and front_max_out and rear_max_out:
        sub = diff_df.loc[out_mask].copy()
        f_norm = sub["front"] / front_max_out
        r_norm = sub["rear"] / rear_max_out
        diff_df.loc[out_mask, "ratio_norm"] = (f_norm - r_norm) * 100.0

    # IQR ベースで表示範囲を決定
    def _compute_limits_ratio(mask: pd.Series) -> tuple[float, float] | tuple[None, None]:
        vals = diff_df.loc[mask, "ratio_norm"].dropna()
        if vals.empty:
            return None, None
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            L = q1 - DIFF_RATIO_IQR_K * iqr
            U = q3 + DIFF_RATIO_IQR_K * iqr
        else:
            L, U = float(vals.min()), float(vals.max())
        lim = max(abs(L), abs(U))
        if not np.isfinite(lim) or lim == 0:
            lim = max(abs(float(vals.min())), abs(float(vals.max())))
        if not np.isfinite(lim) or lim == 0:
            return None, None
        return -lim, lim

    vmin_in, vmax_in = _compute_limits_ratio(in_mask)
    vmin_out, vmax_out = _compute_limits_ratio(out_mask)

    if vmin_in is None and vmin_out is None:
        raise ValueError("diff_ratio_norm の有効な割合データがありません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = diff_df[
                (diff_df["row_facet"] == rlab)
                & (diff_df["col_facet"] == clab)
            ]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[sub["io"] == "in"]
            if vmin_in is not None and not sub_in.empty:
                sc_in = ax.scatter(
                    sub_in["x_abs"],
                    sub_in["y"],
                    c=sub_in["ratio_norm"],
                    cmap="coolwarm",
                    vmin=vmin_in,
                    vmax=vmax_in,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_in = sc_in

            sub_out = sub[sub["io"] == "out"]
            if vmin_out is not None and not sub_out.empty:
                sc_out = ax.scatter(
                    sub_out["x_abs"],
                    sub_out["y"],
                    c=sub_out["ratio_norm"],
                    cmap="coolwarm",
                    vmin=vmin_out,
                    vmax=vmax_out,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (|x|, front/rear folded)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=True,
        )

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    # in/out 用に上下2本のカラーバー（正規化割合用）
    if last_scatter_in is not None and vmin_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("normalized diff [%] (in)")
    if last_scatter_out is not None and vmin_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("normalized diff [%] (out)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def plot_facet_diff_ratio_y(
    df_long: pd.DataFrame,
    dpi: int,
    output: str | None,
    criteria_df: pd.DataFrame | None = None,
    annotate_criteria: bool = False,
    plot_xcenter: bool = False,
    plot_theta_def: bool = False,
):
    """(io, y) ごとに front/rear をロバスト最大で正規化し、その差分[%]を表示するモード。"""
    diff_df = compute_front_rear_diff_fold(df_long)

    row_levels = sorted(diff_df["row_facet"].unique().tolist())
    col_levels = sorted(diff_df["col_facet"].unique().tolist())
    nrows = len(row_levels)
    ncols = len(col_levels)

    x_min = float(diff_df["x_abs"].min())
    x_max = float(diff_df["x_abs"].max())
    y_min = float(diff_df["y"].min())
    y_max = float(diff_df["y"].max())
    x_span = x_max - x_min if np.isfinite(x_max - x_min) and x_max != x_min else 1.0
    y_span = y_max - y_min if np.isfinite(y_max - y_min) and y_max != y_min else 1.0

    # 各パネル(row_facet, col_facet) 内の (io, y) ごとに front/rear のロバスト最大値を計算
    group_keys = ["row_facet", "col_facet", "io", "y"]
    front_max = diff_df.groupby(group_keys)["front"].transform(_robust_group_max)
    rear_max = diff_df.groupby(group_keys)["rear"].transform(_robust_group_max)

    diff_df = diff_df.copy()
    with np.errstate(divide="ignore", invalid="ignore"):
        diff_df["front_norm_y"] = np.where(
            np.isfinite(front_max) & (front_max > 0),
            diff_df["front"] / front_max,
            np.nan,
        )
        diff_df["rear_norm_y"] = np.where(
            np.isfinite(rear_max) & (rear_max > 0),
            diff_df["rear"] / rear_max,
            np.nan,
        )

    diff_df["diff_norm_y"] = (diff_df["front_norm_y"] - diff_df["rear_norm_y"]) * 100.0

    # in/out でスケールを分けて IQR ベースでカラー範囲を決定
    in_mask = diff_df["io"] == "in"
    out_mask = diff_df["io"] == "out"

    def _limits(mask: pd.Series) -> tuple[float, float] | tuple[None, None]:
        vals = diff_df.loc[mask, "diff_norm_y"].dropna()
        if vals.empty:
            return None, None
        q1 = vals.quantile(0.25)
        q3 = vals.quantile(0.75)
        iqr = q3 - q1
        if np.isfinite(iqr) and iqr > 0:
            lo = q1 - DIFF_RATIO_IQR_K * iqr
            hi = q3 + DIFF_RATIO_IQR_K * iqr
        else:
            lo, hi = float(vals.min()), float(vals.max())
        m = max(abs(lo), abs(hi))
        if not np.isfinite(m) or m == 0:
            return None, None
        return -m, m

    vmin_in, vmax_in = _limits(in_mask)
    vmin_out, vmax_out = _limits(out_mask)

    if vmin_in is None and vmin_out is None:
        raise ValueError("diff_ratio_y の有効な差分値がありません。")

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.0 * ncols, 4.0 * nrows),
        sharex=True,
        sharey=True,
    )
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = np.array([axes])
    elif ncols == 1:
        axes = axes[:, np.newaxis]

    last_scatter_in = None
    last_scatter_out = None

    for i, rlab in enumerate(row_levels):
        for j, clab in enumerate(col_levels):
            ax = axes[i, j]
            sub = diff_df[
                (diff_df["row_facet"] == rlab)
                & (diff_df["col_facet"] == clab)
            ]
            if sub.empty:
                ax.set_visible(False)
                continue

            sub_in = sub[sub["io"] == "in"]
            if not sub_in.empty and vmin_in is not None:
                sc_in = ax.scatter(
                    sub_in["x_abs"],
                    sub_in["y"],
                    c=sub_in["diff_norm_y"],
                    cmap="coolwarm",
                    vmin=vmin_in,
                    vmax=vmax_in,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_in = sc_in

            sub_out = sub[sub["io"] == "out"]
            if not sub_out.empty and vmin_out is not None:
                sc_out = ax.scatter(
                    sub_out["x_abs"],
                    sub_out["y"],
                    c=sub_out["diff_norm_y"],
                    cmap="coolwarm",
                    vmin=vmin_out,
                    vmax=vmax_out,
                    s=60,
                    edgecolors="none",
                )
                last_scatter_out = sc_out

            if i == nrows - 1:
                ax.set_xlabel("x [mm] (|x|, front/rear folded)")
            if j == 0:
                ax.set_ylabel("y [mm]")
            ax.set_title("")

    for ax in axes.ravel():
        if ax.get_visible():
            ax.set_xlim(x_min - 0.05 * x_span, x_max + 0.05 * x_span)
            ax.set_ylim(y_min - 0.05 * y_span, y_max + 0.05 * y_span)
            ax.set_aspect("equal", adjustable="box")

    if annotate_criteria and criteria_df is not None and not criteria_df.empty:
        _annotate_criteria_on_facet_axes(axes, row_levels, col_levels, criteria_df)
    if criteria_df is not None and not criteria_df.empty:
        _overlay_criteria_marks_on_facet_axes(
            axes,
            row_levels,
            col_levels,
            criteria_df,
            plot_xcenter=plot_xcenter,
            plot_theta_def=plot_theta_def,
            x_is_abs=True,
        )

    fig.subplots_adjust(left=0.35, right=0.82, top=0.9, bottom=0.12)
    fig.canvas.draw()

    for j, clab in enumerate(col_levels):
        ax = axes[0, j]
        pos = ax.get_position()
        x_center = 0.5 * (pos.x0 + pos.x1)
        y_top = pos.y1 + 0.015
        fig.text(x_center, y_top, clab, ha="center", va="bottom", fontsize=11)

    for i, rlab in enumerate(row_levels):
        ax = axes[i, 0]
        ax.text(
            -0.75,
            0.5,
            rlab,
            transform=ax.transAxes,
            ha="right",
            va="center",
            fontsize=12,
        )

    if last_scatter_in is not None:
        cax_in = fig.add_axes([0.86, 0.55, 0.02, 0.27])
        cbar_in = fig.colorbar(last_scatter_in, cax=cax_in, orientation="vertical")
        cbar_in.set_label("diff_y [%] (in, per y)")
    if last_scatter_out is not None:
        cax_out = fig.add_axes([0.86, 0.18, 0.02, 0.27])
        cbar_out = fig.colorbar(last_scatter_out, cax=cax_out, orientation="vertical")
        cbar_out.set_label("diff_y [%] (out, per y)")

    if output:
        out_path = Path(output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(out_path), dpi=dpi, bbox_inches="tight")
        print(f"保存しました: {out_path}")
    else:
        plt.show()


def main():
    args = parse_args()
    sns.set(context="talk", style=args.style)

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"入力CSVが見つかりません: {input_path}", file=sys.stderr)
        sys.exit(1)

    try:
        df = load_and_filter(input_path, args.target_thrust)
        comp_df = reconstruct_components(df, args.single_angle_mode)
        # 必要なら推定結果をロング形式でエクスポート
        if args.export_components:
            export_components_long(comp_df, args.export_components, args.row_keys, args.col_keys)
        df_long = build_long_with_coordinates(comp_df)
        # ファセット用ラベルを付与
        df_long = add_facet_labels(df_long, args.row_keys, args.col_keys)

        criteria_df = None
        if (
            args.export_criteria
            or args.print_criteria
            or args.annotate_criteria
            or args.plot_xcenter
            or args.plot_theta_def
        ):
            criteria_df = compute_criteria_table(
                df_long,
                args.criteria_field,
                by_y=args.criteria_by_y,
            )
            if args.print_criteria:
                cols = [
                    "row_facet",
                    "col_facet",
                    "y",
                    "io",
                    "side",
                    "criteria_field",
                    "I_asym",
                    "X_center_mm",
                    "theta_def_deg",
                    "n_total",
                ]
                show = [c for c in cols if c in criteria_df.columns]
                df_show = criteria_df[show]
                if args.criteria_by_y and len(df_show) > 200:
                    print(df_show.head(200).to_string(index=False))
                    print(f"... (total rows={len(df_show)})")
                else:
                    print(df_show.to_string(index=False))
            if args.export_criteria:
                out_path = Path(args.export_criteria)
                out_path.parent.mkdir(parents=True, exist_ok=True)
                criteria_df.to_csv(out_path, index=False)
                print(f"Exported criteria table to: {out_path}")
        if args.mode == "diff_fold":
            plot_facet_diff_fold(
                df_long,
                args.dpi,
                args.output,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
        elif args.mode == "diff_ratio":
            plot_facet_diff_ratio(
                df_long,
                args.dpi,
                args.output,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
        elif args.mode == "diff_ratio_norm":
            plot_facet_diff_ratio_norm(
                df_long,
                args.dpi,
                args.output,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
        elif args.mode == "scalar_norm":
            plot_facet_scalar_norm(df_long, args.dpi, args.output)
        elif args.mode == "scalar_norm_y":
            plot_facet_scalar_norm_y(
                df_long,
                args.dpi,
                args.output,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
        elif args.mode == "diff_ratio_y":
            plot_facet_diff_ratio_y(
                df_long,
                args.dpi,
                args.output,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
        else:
            plot_facet_2d(
                df_long,
                args.mode,
                args.dpi,
                args.output,
                cmap_in=args.cmap_in,
                cmap_out=args.cmap_out,
                colorbar_mode=args.colorbar_mode,
                criteria_df=criteria_df,
                annotate_criteria=args.annotate_criteria,
                plot_xcenter=args.plot_xcenter,
                plot_theta_def=args.plot_theta_def,
            )
    except Exception as e:
        print(f"エラー: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()


